routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

require __DIR__.'/auth.php';

Route::get('/', ['as' => 'home', 'uses' => 'HomeController@landingPage'])->middleware(['XSS']);
Route::get('/home', ['as' => 'home', 'uses' => 'HomeController@index'])->middleware(['auth', 'XSS', 'CheckPlan']);
Route::get('/dashboard', ['as' => 'home', 'uses' => 'HomeController@index'])->middleware(['auth', 'XSS', 'CheckPlan']);
Route::get('/appointment-calendar/{id?}', ['as' => 'appointment.calendar', 'uses' => 'AppointmentDeatailController@getCalenderAllData'])->middleware(['auth', 'XSS']);

Route::get('/appointment-note/{id?}', ['as' => 'appointment.add-note', 'uses' => 'AppointmentDeatailController@add_note'])->middleware(['auth', 'XSS']);
Route::post('/appointment-note-store/{id?}', ['as' => 'appointment.note.store', 'uses' => 'AppointmentDeatailController@note_store'])->middleware(['auth', 'XSS']);

Route::get('get-appointment-detail/{id}', ['as' => 'appointment.details', 'uses' => 'AppointmentDeatailController@getAppointmentDetails'])->middleware(['auth', 'XSS']);
Route::resource('business', 'BusinessController')->middleware(['auth', 'XSS', 'CheckPlan']);
Route::group(['middleware' => ['auth', 'XSS', 'CheckPlan']], function () {
    Route::get('business/edit/{id}', ['as' => 'business.edit', 'uses' => 'BusinessController@edit']);
    Route::get('business/theme-edit/{id}', ['as' => 'business.edit2', 'uses' => 'BusinessController@edit2']);
    Route::get('business/analytics/{id}', ['as' => 'business.analytics', 'uses' => 'BusinessController@analytics']);
    Route::post('business/edit-theme/{id}', ['as' => 'business.edit-theme', 'uses' => 'BusinessController@editTheme']);
    Route::post('business/domain-setting/{id}', ['as' => 'business.domain-setting', 'uses' => 'BusinessController@domainsetting']);
    Route::resource('appointments', 'AppointmentDeatailController');
    // Route::get('appoinments/', ['as' => 'appointments.index', 'uses' => 'AppointmentDeatailController@index']);
    Route::resource('users', 'UserController');
    Route::get('user/{id}/plan', 'UserController@upgradePlan')->name('plan.upgrade');
    Route::get('user/{id}/plan/{pid}', 'UserController@activePlan')->name('plan.active');
    Route::get('business/preview/card/{slug}', ['as' => 'business.template', 'uses' => 'BusinessController@getcard']);
    Route::delete('business/destroy/{id}', ['as' => 'business.destroy', 'uses' => 'BusinessController@destroy']);
    Route::get('profile', 'UserController@profile')->name('profile');
    Route::post('edit-profile', 'UserController@editprofile')->name('update.account');
    Route::resource('systems', 'SystemController');
    Route::post('email-settings', 'SystemController@saveEmailSettings')->name('email.settings');
    Route::post('company-settings-store', 'SystemController@storeCompanySetting')->name('company.settings.store');

    Route::post('test-mail', 'SystemController@testMail')->name('test.mail')->middleware(['auth', 'XSS']);
    Route::post('test-mail/send', 'SystemController@testSendMail')->name('test.send.mail')->middleware(['auth', 'XSS']);

    // Route::post('/test',['as' => 'test.email','uses' =>'SettingsController@testEmail'])->middleware(['auth','XSS']);
    // Route::post('/test/send',['as' => 'test.email.send','uses' =>'SettingsController@testEmailSend'])->middleware(['auth','XSS']);

    Route::get('change-language/{lang}', 'UserController@changeLanquage')->name('change.language');
    Route::get('manage-language/{lang}', 'LanguageController@manageLanguage')->name('manage.language');
    Route::post('store-language-data/{lang}', 'LanguageController@storeLanguageData')->name('store.language.data');
    Route::get('create-language', 'LanguageController@createLanguage')->name('create.language');
    Route::post('store-language', 'LanguageController@storeLanguage')->name('store.language');

    Route::delete('/lang/{lang}', 'LanguageController@destroyLang')->name('lang.destroy');
    Route::resource('coupons', 'CouponController');
});

Route::post('stripe-settings', 'SystemController@savePaymentSettings')->name('payment.settings')->middleware(['auth', 'XSS']);
Route::get('/stripe/{code}', 'StripePaymentController@stripe')->name('stripe')->middleware(['auth', 'XSS']);
Route::post('/stripe', 'StripePaymentController@stripePost')->name('stripe.post')->middleware(['auth', 'XSS']);
Route::get('order', 'StripePaymentController@index')->name('order.index')->middleware(['auth', 'XSS']);
Route::any('/plan/error/{flag}', 'PaymentWallPaymentController@paymenterror')->name('callback.error');
Route::any('plan-mercado-callback/{plan_id}', 'MercadoPaymentController@mercadopagoPaymentCallback')->name('plan.mercado.callback')->middleware(['auth']);
Route::resource('plans', 'PlanController');
//================================= Custom Landing Page ====================================//

Route::get('/{slug}', 'BusinessController@getcard');
Route::post('appoinment/make-appointment', ['as' => 'appoinment.store', 'uses' => 'AppointmentDeatailController@store'])->middleware('XSS');

Route::post('change-password', 'UserController@updatePassword')->name('update.password');
Route::get('/download/{slug}', 'BusinessController@getVcardDownload')->name('bussiness.save');

Route::get('/apply-coupon', ['as' => 'apply.coupon', 'uses' => 'CouponController@applyCoupon'])->middleware(['auth', 'XSS']);

Route::post('prepare-payment', ['as' => 'prepare.payment', 'uses' => 'PlanController@preparePayment'])->middleware(['auth', 'XSS']);
Route::get('/payment/{code}', ['as' => 'payment', 'uses' => 'PlanController@payment'])->middleware(['auth', 'XSS']);

Route::post('plan-pay-with-paypal', 'PaypalController@planPayWithPaypal')->name('plan.pay.with.paypal')->middleware(['auth', 'XSS']);

//================================= Plan Payment Gateways  ====================================//

Route::post('/plan-pay-with-paystack', ['as' => 'plan.pay.with.paystack', 'uses' => 'PaystackPaymentController@planPayWithPaystack'])->middleware(['auth', 'XSS']);
Route::get('/plan/paystack/{pay_id}/{plan_id}', ['as' => 'plan.paystack', 'uses' => 'PaystackPaymentController@getPaymentStatus']);

Route::post('/plan-pay-with-flaterwave', ['as' => 'plan.pay.with.flaterwave', 'uses' => 'FlutterwavePaymentController@planPayWithFlutterwave'])->middleware(['auth', 'XSS']);
Route::get('/plan/flaterwave/{txref}/{plan_id}', ['as' => 'plan.flaterwave', 'uses' => 'FlutterwavePaymentController@getPaymentStatus']);

Route::post('/plan-pay-with-razorpay', ['as' => 'plan.pay.with.razorpay', 'uses' => 'RazorpayPaymentController@planPayWithRazorpay'])->middleware(['auth', 'XSS']);
Route::get('/plan/razorpay/{txref}/{plan_id}', ['as' => 'plan.razorpay', 'uses' => 'RazorpayPaymentController@getPaymentStatus']);

Route::post('/plan-pay-with-paytm', ['as' => 'plan.pay.with.paytm', 'uses' => 'PaytmPaymentController@planPayWithPaytm'])->middleware(['auth', 'XSS']);
Route::post('/plan/paytm/{plan}', ['as' => 'plan.paytm', 'uses' => 'PaytmPaymentController@getPaymentStatus']);

Route::post('/plan-pay-with-mercado', ['as' => 'plan.pay.with.mercado', 'uses' => 'MercadoPaymentController@planPayWithMercado'])->middleware(['auth', 'XSS']);
Route::post('/plan/mercado', ['as' => 'plan.mercado', 'uses' => 'MercadoPaymentController@getPaymentStatus']);

Route::post('/plan-pay-with-mollie', ['as' => 'plan.pay.with.mollie', 'uses' => 'MolliePaymentController@planPayWithMollie'])->middleware(['auth', 'XSS']);
Route::get('/plan/mollie/{plan}', ['as' => 'plan.mollie', 'uses' => 'MolliePaymentController@getPaymentStatus']);

Route::post('/plan-pay-with-skrill', ['as' => 'plan.pay.with.skrill', 'uses' => 'SkrillPaymentController@planPayWithSkrill'])->middleware(['auth', 'XSS']);
Route::get('/plan/skrill/{plan}', ['as' => 'plan.skrill', 'uses' => 'SkrillPaymentController@getPaymentStatus']);

Route::post('/plan-pay-with-coingate', ['as' => 'plan.pay.with.coingate', 'uses' => 'CoingatePaymentController@planPayWithCoingate'])->middleware(['auth', 'XSS']);
Route::get('/plan/coingate/{plan}', ['as' => 'plan.coingate', 'uses' => 'CoingatePaymentController@getPaymentStatus']);

Route::get('{id}/plan-get-payment-status', 'PaypalController@planGetPaymentStatus')->name('plan.get.payment.status')->middleware(
    [
        'auth',
        'XSS',
    ]
);

Route::get('business/{slug}/get_card', 'BusinessController@cardpdf')->name('get.card');
Route::get('businessqr/download/', 'BusinessController@downloadqr')->name('download.qr');

// Route::get('business/card', 'BusinessController@card')->name('get.card');

Route::post('business/block-setting/{id}', ['as' => 'business.block-setting', 'uses' => 'BusinessController@blocksetting'])->middleware(
    [
        'auth',
        'XSS',
    ]
);

//=================================Plan Request Module ====================================//
Route::get('plan_request/index', 'PlanRequestController@index')->name('plan_request.index')->middleware(['auth', 'XSS']);
Route::get('request_frequency/{id}', 'PlanRequestController@requestView')->name('request.view')->middleware(['auth', 'XSS']);
Route::get('request_send/{id}', 'PlanRequestController@userRequest')->name('send.request')->middleware(['auth', 'XSS']);
Route::get('request_response/{id}/{response}', 'PlanRequestController@acceptRequest')->name('response.request')->middleware(['auth', 'XSS']);
Route::get('request_cancel/{id}', 'PlanRequestController@cancelRequest')->name('request.cancel')->middleware(['auth', 'XSS']);

/*==================================Recaptcha====================================================*/

resources/views/business/addField.blade.php
function GetSelectedTextValue(select_template) {
        var selectedText = select_template.options[select_template.selectedIndex].innerHTML;
        var selectedValue = select_template.value;
        if(selectedValue == 'custom_field'){
            var html = `
              <div class="row">
                <div class="col-12">
                    <label class="form-control-label">Label</label>
                    <input class="form-control" type="text" name="${selectedValue}_label">
                </div>
                <div class="col-12">
                    <label class="form-control-label">custom field</label>
                    <input class="form-control" type="text" name="${selectedValue}">
                </div>  
              </div>
          `;
        }
        else{
            var html = `
              <div class="row">
                <div class="col-12">
                    <label class="form-control-label">${selectedValue}</label>
                    <input class="form-control" type="text" name="${selectedValue}">
                </div>  
              </div>
          `;
        }
        
        document.getElementById('addnewfield').html=html;
      }

resources/views/business/analytics.blade.php
@extends('layouts.admin')
@section('page-title')
   {{__('Business Analytics')}}
@endsection
@section('title')
   {{__('Business Analytics')}}
@endsection
@section('breadcrumb')
    <li class="breadcrumb-item active" aria-current="page"><a href="{{ route('business.index') }}">{{__('Business')}}</a></li>
    <li class="breadcrumb-item active" aria-current="page">{{__('Business Analytics')}}</li>
@endsection
@section('content')

<div class="row">
    <div class="col-xl-6 col-md-12">
        <div class="card">
            <div class="card-header">
                <div class="float-end">
                    <span class="mb-0 float-right">{{__('Last 15 Days')}}</span>
                </div>
                <h5>{{__('Appointments')}}</h5>
            </div>
            <div class="card-body">
                <div id="apex-storedashborad" data-color="primary" data-height="280"></div>
            </div>
        </div>
    </div>   
    <div class="col-xl-6 col-md-12">
        <div class="card">
            <div class="card-header">
                <div class="float-end">
                    <span class="mb-0 text-sm float-right mt-1">{{__('Last 15 Days')}}</span>
                </div>
                <h5 class="mb-0 float-left">{{('Platform')}}</h5>
            </div>
            <div class="card-body">
                <div class="row align-items-center">
                        <div id="user_platform-chart"></div>
                </div>
            </div>
        </div>
    </div> 
</div>    
<div class="row">
    <div class="col-xl-6 col-md-6 col-sm-6">
        <div class="card">
            <div class="card-header">
                <div class="float-end">
                    <span class="mb-0 text-sm float-right mt-1">{{__('Last 15 Days')}}</span>
                </div>
                <h5 class="mb-0 float-left">{{__('Device Analytics')}}</h5>
            </div>
            <div class="card-body">
                <div class="row align-items-center">
                        <div id="pie-storedashborad"></div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-6 col-md-6 col-sm-6">
        <div class="card">
            <div class="card-header">
                <div class="float-end">
                    <span class="mb-0 text-sm float-right mt-1">{{__('Last 15 Days')}}</span>
                </div>
                <h5 class="mb-0 float-left">{{__('Browser Analytics')}}</h5>
            </div>
            <div class="card-body">
                <div class="row align-items-center">
                        <div id="pie-storebrowser"></div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-4 col-md-4 col-sm-6">
        
    </div>            
</div>

@endsection
@push('custom-scripts')
    <script src="{{ asset('custom/js/purpose.js') }}"></script>
    <script>
        (function () {
        var options = {
            chart: {
                height: 350,
                type: 'line',
                toolbar: {
                    show: false,
                },
            },
            dataLabels: {
                enabled: false
            },
            stroke: {
                width: 2,
                curve: 'smooth'
            },
            series : {!! json_encode($chartData['data']) !!},
            xaxis: {labels: {format: "MMM", style: {colors: PurposeStyle.colors.gray[600], fontSize: "14px", fontFamily: PurposeStyle.fonts.base, cssClass: "apexcharts-xaxis-label"}}, axisBorder: {show: !1}, axisTicks: {show: !0, borderType: "solid", color: PurposeStyle.colors.gray[300], height: 6, offsetX: 0, offsetY: 0}, type: "text", categories: {!! json_encode($chartData['label']) !!}},
            yaxis: {labels: {style: {color: PurposeStyle.colors.gray[600], fontSize: "12px", fontFamily: PurposeStyle.fonts.base}}, axisBorder: {show: !1}, axisTicks: {show: !0, borderType: "solid", color: PurposeStyle.colors.gray[300], height: 6, offsetX: 0, offsetY: 0}},

            grid: {
                strokeDashArray: 4,
            },
            legend: {
                position: 'top',
                horizontalAlign: 'right',
                floating: true,
                offsetY: -25,
                offsetX: -5
            },
            // markers: {
            //     size: 4,
            //     colors: ['#ffa21d', '#FF3A6E'],
            //     opacity: 0.9,
            //     strokeWidth: 2,
            //     hover: {
            //         size: 7,
            //     }
            // },
        };
        var chart = new ApexCharts(document.querySelector("#apex-storedashborad"), options);
        chart.render();
    })();
        var options = {
            chart: {
                height: 200,
                type: 'donut',
            },
            dataLabels: {
                enabled: true,
            },
            series: {!! json_encode($devicearray['data']) !!},
            colors: ["#CECECE", '#ffa21d', '#FF3A6E', '#3ec9d6'],
            labels: {!! json_encode($devicearray['label']) !!},
            legend: {
                show: true,
                position: 'bottom',
            },
        };
        var chart = new ApexCharts(document.querySelector("#pie-storedashborad"), options);
        chart.render();
        var options = {
            chart: {
                height:200,
                type: 'donut',
            },
            dataLabels: {
                enabled: true,
            },
            series: {!! json_encode($browserarray['data']) !!},
            colors: ["#CECECE", '#ffa21d', '#FF3A6E', '#3ec9d6'],
            labels: {!! json_encode($browserarray['label']) !!},
            legend: {
                show: true,
                position: 'bottom',
            },
        };
        var chart = new ApexCharts(document.querySelector("#pie-storebrowser"), options);
        chart.render();
    </script>
    <script>
        var WorkedHoursChart = (function () {
            var $chart = $('#user_platform-chart');

            function init($this) {
                var options = {
                    chart: {
                        height: 250,
                        type: 'bar',
                        zoom: {
                            enabled: false
                        },
                        toolbar: {
                            show: false
                        },
                        shadow: {
                            enabled: false,
                        },

                    },
                    plotOptions: {
                bar: {
                    columnWidth: '30%',
                    borderRadius: 10,
                    dataLabels: {
                        position: 'top',
                    },
                }
            },
                    stroke: {
                show: true,
                width: 1,
                colors: ['#fff']
            },
                    series: [{
                        name: 'Platform',
                        data: {!! json_encode($platformarray['data']) !!},
                    }],
                    xaxis: {
                        labels: {
                            // format: 'MMM',
                            style: {
                                colors: PurposeStyle.colors.gray[600],
                                fontSize: '14px',
                                fontFamily: PurposeStyle.fonts.base,
                                cssClass: 'apexcharts-xaxis-label',
                            },
                        },
                        axisBorder: {
                            show: false
                        },
                        axisTicks: {
                            show: true,
                            borderType: 'solid',
                            color: PurposeStyle.colors.gray[300],
                            height: 6,
                            offsetX: 0,
                            offsetY: 0
                        },
                        title: {
                            text: '{{__('Platform')}}'
                        },
                        categories: {!! json_encode($platformarray['label']) !!},
                    },
                    yaxis: {
                        labels: {
                            style: {
                                color: PurposeStyle.colors.gray[600],
                                fontSize: '12px',
                                fontFamily: PurposeStyle.fonts.base,
                            },
                        },
                        axisBorder: {
                            show: false
                        },
                        axisTicks: {
                            show: true,
                            borderType: 'solid',
                            color: PurposeStyle.colors.gray[300],
                            height: 6,
                            offsetX: 0,
                            offsetY: 0
                        }
                    },
                    fill: {
                        type: 'solid',
                        opacity: 1

                    },
                    markers: {
                        size: 4,
                        opacity: 0.7,
                        strokeColor: "#fff",
                        strokeWidth: 3,
                        hover: {
                            size: 7,
                        }
                    },
                    grid: {
                        borderColor: PurposeStyle.colors.gray[300],
                        strokeDashArray: 5,
                    },
                    dataLabels: {
                        enabled: false
                    }
                }
                // Get data from data attributes
                var dataset = $this.data().dataset,
                    labels = $this.data().labels,
                    color = $this.data().color,
                    height = $this.data().height,
                    type = $this.data().type;

                // Inject synamic properties
                // options.colors = [
                //     PurposeStyle.colors.theme[color]
                // ];
                // options.markers.colors = [
                //     PurposeStyle.colors.theme[color]
                // ];
                options.chart.height = height ? height : 350;
                // Init chart
                var chart = new ApexCharts($this[0], options);
                // Draw chart
                setTimeout(function () {
                    chart.render();
                }, 300);
            }
            // Events
            if ($chart.length) {
                $chart.each(function () {
                    init($(this));
                });
            }
        })();
    </script>
@endpush

resources/views/business/businessQR.blade.php
@php
    // $logo_img=\App\Models\Utility::getValByName('logo'); 
    $company_logo = \App\Models\Utility::GetLogo();
    $logo=\App\Models\Utility::get_file('uploads/logo/');
@endphp
<style>
    .qrcode canvas {
    width: 100%;
    height: 100%;
    padding: 12px 25px;
}
</style>
<div class="logo-content modal-body-section text-center">
    {{-- <a href="{{asset(Storage::url($logo_img))}}" target="_blank">
        <img src="{{asset(Storage::url($logo_img))}}" class="big-logo" id="company_logo_update">    
    </a>  --}}
    <img src="{{ $logo . (isset($company_logo) && !empty($company_logo) ? $company_logo : 'logo-dark.png') }}"
    alt="{{ config('app.name', 'AccountGo') }}" class="logo logo-lg">
</div>
<div class="modal-body border-0">
    <div class="modal-body-section text-center">
        <div class="qr-main-image">
            <div class="qr-code-border">
                <img src="{{asset('custom/img/left-top.svg')}}" alt="left-top" class="img-fluid left-top-border">
                <img src="{{asset('custom/img/left-bottom.svg')}}" alt="left-bottom" class="img-fluid left-bottom-border">
                <img src="{{asset('custom/img/right-top.svg')}}" alt="right-top" class="img-fluid right-top-border">
                <img src="{{asset('custom/img/right-bottom.svg')}}" alt="right-bottom" class="img-fluid right-bottom-border">
                <div class="qrcode mt-3 "></div>
            </div>
        </div>
        <div class="text">
            <p class="text-black">
                {{__('Point your camera at the QR code, or visit')}}<br> <span class="qr-link text-center mr-2"></span>
            </p>
        </div>
    </div>
</div>
<script> 
    // $("#download-qr").load(function(){ 
    //     // alert("hey");
    //     var qrcode = '{{$business->slug}}';  
    //     $(".qrcode").children("canvas").addClass( "data");
    //     this.href = $('.data')[0].toDataURL();
    //     this.download = '{{$business->slug}}';
    // });
    $( document ).ready(function() {
        // dd(url_link);
        var slug = '{{$qrData}}';
        var url_link = `{{ url("/") }}/${slug}`;
        console.log(url_link);
        $(`.qr-link`).text(url_link);
        $('.qrcode').qrcode(url_link); 
    }); 
</script>

resources/views/business/create.blade.php
{{ Form::open(array('url' => route('business.store')))}}
    <div class="row">
        <div class="col-12">
            {{Form::label('Business',__('Business'),['class'=>'form-control-label'])}}
            {{Form::text('title',null,array('class'=>'form-control mt-2'))}}
            @error('title')
                <span class="invalid-favicon text-xs text-danger" role="alert">{{ $message }}</span>
            @enderror
        </div>  
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary btn-light" data-bs-dismiss="modal">{{ __('Cancel') }}</button>
        <input class="btn btn-primary" type="submit" value="{{ __('Create') }}">
    </div>
  

resources/views/business/index.blade.php
@extends('layouts.admin')
@section('page-title')
   {{__('Business')}}
@endsection
@section('title')
   {{__('Business')}}
@endsection
@section('breadcrumb')
    <li class="breadcrumb-item active" aria-current="page">{{__('Business')}}</li>
@endsection
@section('action-btn')
    <div class="col-xl-8 col-lg-8 col-md-8 d-flex align-items-center justify-content-between justify-content-md-end" data-bs-placement="top" data-bs-toggle="tooltip"
    data-bs-original-title="{{__('Create Business')}}">
                        <a href="#" class="btn btn-sm btn-primary btn-icon m-1" 
                data-bs-target="#exampleModal" data-url="{{ route('business.create') }}"
                data-bs-whatever="{{__('Create Business')}}" data-bs-toggle="modal"
            > <span class="text-white"> 
                    <i class="ti ti-plus text-white" ></i></span>
            </a>
    </div>
@endsection
@section('content')
<div class="col-xl-12">
    <div class="card">
        <div class="card-body table-border-style">
            <h5></h5>
            <div class="table-responsive">
                <table class="table" id="pc-dt-simple">
                    <br>
                    <thead>
                        <tr>
                            <th>{{__('No')}}</th>
                            <th>{{__('Businesses')}}</th>
                            <th class="text-end">{{__('Operations')}}</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($business as $val)
                            <tr>
                                <td>{{ $loop->index+1 }}</td>
                                <td class="align-middle">
                                    <a class="btn btn-outline-primary" style="min-width: 180px;" href="{{ route('business.edit',$val->id) }}"><b>{{ $val->title }}</b></a>
                                </td>
                                <div class="row ">
                                    <td class="text-end">
                                        @if($val->status !='lock')
                                            <div class="action-btn bg-success  ms-2">
                                                <a href="#" class="mx-3 btn btn-sm d-inline-flex align-items-center cp_link" data-link="{{url('/'.$val->slug)}}" data-bs-toggle="tooltip"
                                                    data-bs-original-title="{{__('Click to copy card link')}}"> <span class="text-white"> <i
                                                            class="ti ti-copy text-white"></i></span></a>
                                            </div>
                                            <div class="action-btn bg-info  ms-2">
                                                <a href="{{ route('business.analytics',$val->id) }}" class="mx-3 btn btn-sm d-inline-flex align-items-center"  data-bs-toggle="tooltip"
                                                    data-bs-original-title="{{__('Business Analytics')}}"> <span class="text-white"> <i
                                                            class="ti ti-brand-google-analytics  text-white"></i></span></a>
                                            </div>
                                            <div class="action-btn bg-warning  ms-2">
                                                <a href="{{ route('appointment.calendar',$val->id) }}" class="mx-3 btn btn-sm d-inline-flex align-items-center" data-bs-toggle="tooltip"
                                                    data-bs-original-title="{{__('Business Calender')}}"> <span class="text-white"> <i
                                                            class="ti ti-calendar text-white"></i></span></a>
                                            </div>
                                            <div class="action-btn bg-success  ms-2">
                                                <a href="{{ route('business.edit',$val->id) }}" class="mx-3 btn btn-sm d-inline-flex align-items-center" data-bs-toggle="tooltip"
                                                    data-bs-original-title="{{__('Business Edit')}}"> <span class="text-white"> <i
                                                            class="ti ti-edit text-white"></i></span></a>
                                            </div>
                                            <div class="action-btn bg-warning  ms-2">
                                                <a href="{{ route('business.contacts.show',$val->id) }}" class="mx-3 btn btn-sm d-inline-flex align-items-center" data-bs-toggle="tooltip"
                                                    data-bs-original-title="{{__('Business Contacts')}}"> <span class="text-white"> <i
                                                            class="ti ti-phone text-white"></i></span></a>
                                            </div>
                                            <div class="action-btn bg-danger ms-2">
                                                <a href="#" class="bs-pass-para mx-3 btn btn-sm d-inline-flex align-items-center"  data-confirm="{{__('Are You Sure?')}}" data-text="{{__('This action can not be undone. Do you want to continue?')}}" data-confirm-yes="delete-form-{{$val->id}}" title="{{__('Delete')}}" data-bs-toggle="tooltip" data-bs-placement="top"><span class="text-white"><i class="ti ti-trash"></i></span></a>
                                            </div>
                                            {!! Form::open(['method' => 'DELETE', 'route' => ['business.destroy', $val->id],'id'=>'delete-form-'.$val->id]) !!}
                                            {!! Form::close() !!}
                                                @else
                                            <span class="edit-icon align-middle bg-gray" ><i class="fas fa-lock text-white"></i></span>
                                        @endif
                                    </td>  
                                </div>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection
@push('custom-scripts')
<script type="text/javascript">
   $('.cp_link').on('click', function () {
        var value = $(this).attr('data-link');
        var $temp = $("<input>");
        $("body").append($temp);
        $temp.val(value).select();
        document.execCommand("copy");
        $temp.remove();
        toastrs('{{__('Success')}}', '{{__('Link Copy on Clipboard')}}', 'success');
    });
</script>
@endpush