routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

require __DIR__.'/auth.php';

Route::get('/', ['as' => 'home', 'uses' => 'HomeController@landingPage'])->middleware(['XSS']);
Route::get('/home', ['as' => 'home', 'uses' => 'HomeController@index'])->middleware(['auth', 'XSS', 'CheckPlan']);
Route::get('/dashboard', ['as' => 'home', 'uses' => 'HomeController@index'])->middleware(['auth', 'XSS', 'CheckPlan']);
Route::get('/appointment-calendar/{id?}', ['as' => 'appointment.calendar', 'uses' => 'AppointmentDeatailController@getCalenderAllData'])->middleware(['auth', 'XSS']);

Route::get('/appointment-note/{id?}', ['as' => 'appointment.add-note', 'uses' => 'AppointmentDeatailController@add_note'])->middleware(['auth', 'XSS']);
Route::post('/appointment-note-store/{id?}', ['as' => 'appointment.note.store', 'uses' => 'AppointmentDeatailController@note_store'])->middleware(['auth', 'XSS']);

Route::get('get-appointment-detail/{id}', ['as' => 'appointment.details', 'uses' => 'AppointmentDeatailController@getAppointmentDetails'])->middleware(['auth', 'XSS']);
Route::resource('business', 'BusinessController')->middleware(['auth', 'XSS', 'CheckPlan']);
Route::group(['middleware' => ['auth', 'XSS', 'CheckPlan']], function () {
    Route::get('business/edit/{id}', ['as' => 'business.edit', 'uses' => 'BusinessController@edit']);
    Route::get('business/theme-edit/{id}', ['as' => 'business.edit2', 'uses' => 'BusinessController@edit2']);
    Route::get('business/analytics/{id}', ['as' => 'business.analytics', 'uses' => 'BusinessController@analytics']);
    Route::post('business/edit-theme/{id}', ['as' => 'business.edit-theme', 'uses' => 'BusinessController@editTheme']);
    Route::post('business/domain-setting/{id}', ['as' => 'business.domain-setting', 'uses' => 'BusinessController@domainsetting']);
    Route::resource('appointments', 'AppointmentDeatailController');
    // Route::get('appoinments/', ['as' => 'appointments.index', 'uses' => 'AppointmentDeatailController@index']);
    Route::resource('users', 'UserController');
    Route::get('user/{id}/plan', 'UserController@upgradePlan')->name('plan.upgrade');
    Route::get('user/{id}/plan/{pid}', 'UserController@activePlan')->name('plan.active');
    Route::get('business/preview/card/{slug}', ['as' => 'business.template', 'uses' => 'BusinessController@getcard']);
    Route::delete('business/destroy/{id}', ['as' => 'business.destroy', 'uses' => 'BusinessController@destroy']);
    Route::get('profile', 'UserController@profile')->name('profile');
    Route::post('edit-profile', 'UserController@editprofile')->name('update.account');
    Route::resource('systems', 'SystemController');
    Route::post('email-settings', 'SystemController@saveEmailSettings')->name('email.settings');
    Route::post('company-settings-store', 'SystemController@storeCompanySetting')->name('company.settings.store');

    Route::post('test-mail', 'SystemController@testMail')->name('test.mail')->middleware(['auth', 'XSS']);
    Route::post('test-mail/send', 'SystemController@testSendMail')->name('test.send.mail')->middleware(['auth', 'XSS']);

    // Route::post('/test',['as' => 'test.email','uses' =>'SettingsController@testEmail'])->middleware(['auth','XSS']);
    // Route::post('/test/send',['as' => 'test.email.send','uses' =>'SettingsController@testEmailSend'])->middleware(['auth','XSS']);

    Route::get('change-language/{lang}', 'UserController@changeLanquage')->name('change.language');
    Route::get('manage-language/{lang}', 'LanguageController@manageLanguage')->name('manage.language');
    Route::post('store-language-data/{lang}', 'LanguageController@storeLanguageData')->name('store.language.data');
    Route::get('create-language', 'LanguageController@createLanguage')->name('create.language');
    Route::post('store-language', 'LanguageController@storeLanguage')->name('store.language');

    Route::delete('/lang/{lang}', 'LanguageController@destroyLang')->name('lang.destroy');
    Route::resource('coupons', 'CouponController');
});

Route::post('stripe-settings', 'SystemController@savePaymentSettings')->name('payment.settings')->middleware(['auth', 'XSS']);
Route::get('/stripe/{code}', 'StripePaymentController@stripe')->name('stripe')->middleware(['auth', 'XSS']);
Route::post('/stripe', 'StripePaymentController@stripePost')->name('stripe.post')->middleware(['auth', 'XSS']);
Route::get('order', 'StripePaymentController@index')->name('order.index')->middleware(['auth', 'XSS']);
Route::any('/plan/error/{flag}', 'PaymentWallPaymentController@paymenterror')->name('callback.error');
Route::any('plan-mercado-callback/{plan_id}', 'MercadoPaymentController@mercadopagoPaymentCallback')->name('plan.mercado.callback')->middleware(['auth']);
Route::resource('plans', 'PlanController');
//================================= Custom Landing Page ====================================//

Route::get('/{slug}', 'BusinessController@getcard');
Route::post('appoinment/make-appointment', ['as' => 'appoinment.store', 'uses' => 'AppointmentDeatailController@store'])->middleware('XSS');

Route::post('change-password', 'UserController@updatePassword')->name('update.password');
Route::get('/download/{slug}', 'BusinessController@getVcardDownload')->name('bussiness.save');

Route::get('/apply-coupon', ['as' => 'apply.coupon', 'uses' => 'CouponController@applyCoupon'])->middleware(['auth', 'XSS']);

Route::post('prepare-payment', ['as' => 'prepare.payment', 'uses' => 'PlanController@preparePayment'])->middleware(['auth', 'XSS']);
Route::get('/payment/{code}', ['as' => 'payment', 'uses' => 'PlanController@payment'])->middleware(['auth', 'XSS']);

Route::post('plan-pay-with-paypal', 'PaypalController@planPayWithPaypal')->name('plan.pay.with.paypal')->middleware(['auth', 'XSS']);

//================================= Plan Payment Gateways  ====================================//

Route::post('/plan-pay-with-paystack', ['as' => 'plan.pay.with.paystack', 'uses' => 'PaystackPaymentController@planPayWithPaystack'])->middleware(['auth', 'XSS']);
Route::get('/plan/paystack/{pay_id}/{plan_id}', ['as' => 'plan.paystack', 'uses' => 'PaystackPaymentController@getPaymentStatus']);

Route::post('/plan-pay-with-flaterwave', ['as' => 'plan.pay.with.flaterwave', 'uses' => 'FlutterwavePaymentController@planPayWithFlutterwave'])->middleware(['auth', 'XSS']);
Route::get('/plan/flaterwave/{txref}/{plan_id}', ['as' => 'plan.flaterwave', 'uses' => 'FlutterwavePaymentController@getPaymentStatus']);

Route::post('/plan-pay-with-razorpay', ['as' => 'plan.pay.with.razorpay', 'uses' => 'RazorpayPaymentController@planPayWithRazorpay'])->middleware(['auth', 'XSS']);
Route::get('/plan/razorpay/{txref}/{plan_id}', ['as' => 'plan.razorpay', 'uses' => 'RazorpayPaymentController@getPaymentStatus']);

Route::post('/plan-pay-with-paytm', ['as' => 'plan.pay.with.paytm', 'uses' => 'PaytmPaymentController@planPayWithPaytm'])->middleware(['auth', 'XSS']);
Route::post('/plan/paytm/{plan}', ['as' => 'plan.paytm', 'uses' => 'PaytmPaymentController@getPaymentStatus']);

Route::post('/plan-pay-with-mercado', ['as' => 'plan.pay.with.mercado', 'uses' => 'MercadoPaymentController@planPayWithMercado'])->middleware(['auth', 'XSS']);
Route::post('/plan/mercado', ['as' => 'plan.mercado', 'uses' => 'MercadoPaymentController@getPaymentStatus']);

Route::post('/plan-pay-with-mollie', ['as' => 'plan.pay.with.mollie', 'uses' => 'MolliePaymentController@planPayWithMollie'])->middleware(['auth', 'XSS']);
Route::get('/plan/mollie/{plan}', ['as' => 'plan.mollie', 'uses' => 'MolliePaymentController@getPaymentStatus']);

Route::post('/plan-pay-with-skrill', ['as' => 'plan.pay.with.skrill', 'uses' => 'SkrillPaymentController@planPayWithSkrill'])->middleware(['auth', 'XSS']);
Route::get('/plan/skrill/{plan}', ['as' => 'plan.skrill', 'uses' => 'SkrillPaymentController@getPaymentStatus']);

Route::post('/plan-pay-with-coingate', ['as' => 'plan.pay.with.coingate', 'uses' => 'CoingatePaymentController@planPayWithCoingate'])->middleware(['auth', 'XSS']);
Route::get('/plan/coingate/{plan}', ['as' => 'plan.coingate', 'uses' => 'CoingatePaymentController@getPaymentStatus']);

Route::get('{id}/plan-get-payment-status', 'PaypalController@planGetPaymentStatus')->name('plan.get.payment.status')->middleware(
    [
        'auth',
        'XSS',
    ]
);

Route::get('business/{slug}/get_card', 'BusinessController@cardpdf')->name('get.card');
Route::get('businessqr/download/', 'BusinessController@downloadqr')->name('download.qr');

// Route::get('business/card', 'BusinessController@card')->name('get.card');

Route::post('business/block-setting/{id}', ['as' => 'business.block-setting', 'uses' => 'BusinessController@blocksetting'])->middleware(
    [
        'auth',
        'XSS',
    ]
);

//=================================Plan Request Module ====================================//
Route::get('plan_request/index', 'PlanRequestController@index')->name('plan_request.index')->middleware(['auth', 'XSS']);
Route::get('request_frequency/{id}', 'PlanRequestController@requestView')->name('request.view')->middleware(['auth', 'XSS']);
Route::get('request_send/{id}', 'PlanRequestController@userRequest')->name('send.request')->middleware(['auth', 'XSS']);
Route::get('request_response/{id}/{response}', 'PlanRequestController@acceptRequest')->name('response.request')->middleware(['auth', 'XSS']);
Route::get('request_cancel/{id}', 'PlanRequestController@cancelRequest')->name('request.cancel')->middleware(['auth', 'XSS']);

/*==================================Recaptcha====================================================*/

resources/views/partials/admin/footer.blade.php
<script src="{{asset('custom/js/jquery.min.js')}}"></script>

<script src="{{ asset('assets/js/plugins/popper.min.js') }}"></script>
<script src="{{ asset('assets/js/plugins/perfect-scrollbar.min.js') }}"></script>
<script src="{{ asset('assets/js/plugins/bootstrap.min.js') }}"></script>
<script src="{{asset('assets/js/pages/wow.min.js')}}"></script>
<script src="{{ asset('assets/js/plugins/feather.min.js') }}"></script>
<script src="{{ asset('assets/js/dash.js') }}"></script>
<script src="{{asset('custom/libs/summernote/summernote-bs4.js')}}"></script>
<script src="{{ asset('custom/libs/bootstrap-notify/bootstrap-notify.min.js')}}"></script>
{{-- FullCalendar --}}
<script src="{{ asset('assets/js/plugins/apexcharts.min.js')}}"></script>
<script src="{{ asset('assets/js/plugins/main.min.js') }}"></script>

<!-- sweet alert Js -->
<script src="{{ asset('assets/js/plugins/sweetalert2.all.min.js') }}"></script>
<script src="{{ asset('assets/js/pages/ac-alert.js') }}"></script>
<script src="{{ asset('assets/js/plugins/choices.min.js') }}"></script>
{{-- DataTable --}}
<script src="{{ asset('custom/js/emojionearea.min.js')}}"></script>
<script src="{{ asset('assets/js/plugins/simple-datatables.js')}}"></script>

<script src="{{ asset('custom/js/summernote-ext-emoji.js')}}"></script>
 <script src="{{ asset('assets/js/plugins/bootstrap-switch-button.min.js') }}"></script>

<script>
    const dataTable = new simpleDatatables.DataTable("#pc-dt-simple");
</script>
<script src="{{ asset('custom/js/custom.js')}}"></script>
{{-- MODAL --}}
 @stack('custom-scripts')

<script>
  feather.replace();
  var pctoggle = document.querySelector("#pct-toggler");
  if (pctoggle) {
    pctoggle.addEventListener("click", function () {
      if (
        !document.querySelector(".pct-customizer").classList.contains("active")
      ) {
        document.querySelector(".pct-customizer").classList.add("active");
      } else {
        document.querySelector(".pct-customizer").classList.remove("active");
      }
    });
  }

  var themescolors = document.querySelectorAll(".themes-color > a");
  for (var h = 0; h < themescolors.length; h++) {
    var c = themescolors[h];

    c.addEventListener("click", function (event) {
      var targetElement = event.target;
      if (targetElement.tagName == "SPAN") {
        targetElement = targetElement.parentNode;
      }
      var temp = targetElement.getAttribute("data-value");
      removeClassByPrefix(document.querySelector("body"), "theme-");
      document.querySelector("body").classList.add(temp);
    });
  }

  var custthemebg = document.querySelector("#cust-theme-bg");
  custthemebg.addEventListener("click", function () {
    if (custthemebg.checked) {
      document.querySelector(".dash-sidebar").classList.add("transprent-bg");
      document
        .querySelector(".dash-header:not(.dash-mob-header)")
        .classList.add("transprent-bg");
    } else {
      document.querySelector(".dash-sidebar").classList.remove("transprent-bg");
      document
        .querySelector(".dash-header:not(.dash-mob-header)")
        .classList.remove("transprent-bg");
    }
  });
  function removeClassByPrefix(node, prefix) {
    for (let i = 0; i < node.classList.length; i++) {
      let value = node.classList[i];
      if (value.startsWith(prefix)) {
        node.classList.remove(value);
      }
    }
  }
</script>



@if(Utility::getValByName('gdpr_cookie') == 'on')
    <script type="text/javascript">

        var defaults = {
            'messageLocales': {
                /*'en': 'We use cookies to make sure you can have the best experience on our website. If you continue to use this site we assume that you will be happy with it.'*/
                'en': "{{Utility::getValByName('cookie_text')}}"
            },
            'buttonLocales': {
                'en': 'Ok'
            },
            'cookieNoticePosition': 'bottom',
            'learnMoreLinkEnabled': false,
            'learnMoreLinkHref': '/cookie-banner-information.html',
            'learnMoreLinkText': {
                'it': 'Saperne di più',
                'en': 'Learn more',
                'de': 'Mehr erfahren',
                'fr': 'En savoir plus'
            },
            'buttonLocales': {
                'en': 'Ok'
            },
            'expiresIn': 30,
            'buttonBgColor': '#d35400',
            'buttonTextColor': '#fff',
            'noticeBgColor': '#000',
            'noticeTextColor': '#fff',
            'linkColor': '#009fdd'
        };
    </script>
    <script src="{{ asset('custom/js/cookie.notice.js')}}"></script>
@endif




<script>

    function toastrs(title, message, type) {
    var o, i;
    var icon = '';
    var cls = '';
    if (type == 'success') {
        icon = 'fas fa-check-circle';
        // cls = 'success';
        cls = 'primary';
    } else {
        icon = 'fas fa-times-circle';
        cls = 'danger';
    }

    console.log(type,cls);
    $.notify({ icon: icon, title: " " + title, message: message, url: "" }, {
        element: "body",
        type: cls,
        allow_dismiss: !0,
        placement: {
            from: 'top',
            align: 'right'
        },
        offset: { x: 15, y: 15 },
        spacing: 10,
        z_index: 1080,
        delay: 2500,
        timer: 2000,
        url_target: "_blank",
        mouse_over: !1,
        animate: { enter: o, exit: i },
        // danger
        template: '<div class="toast text-white bg-'+cls+' fade show" role="alert" aria-live="assertive" aria-atomic="true">'
                +'<div class="d-flex">'
                    +'<div class="toast-body"> '+message+' </div>'
                    +'<button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>'
                +'</div>'
            +'</div>'
        // template: '<div class="alert alert-{0} alert-icon alert-group alert-notify" data-notify="container" role="alert"><div class="alert-group-prepend alert-content"><span class="alert-group-icon"><i data-notify="icon"></i></span></div><div class="alert-content"><strong data-notify="title">{1}</strong><div data-notify="message">{2}</div></div><button type="button" class="close" data-notify="dismiss" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>'
    });
}
</script>

<!-- <script type="text/javascript">
 
     $('.show_confirm').click(function(event) {
          var form =  $(this).closest("form");
          var name = $(this).data("name");
          event.preventDefault();
          swal({
              title: `Are you sure?`,
              text: "This action can not be undone. Do you want to continue?",
              icon: "warning",
              buttons: ["No", "Yes"],
              dangerMode: true,
              confirmButtonText: 'Yes',
              cancelButtonText: 'No',
          })
          .then((willDelete) => {
            if (willDelete) {
              form.submit();
            }
          });
      });

     
  
</script> -->
<!-- <script type="text/javascript">
        $(document).ready(function() {
            $('.show_confirm').click(function(event) {
                var form = $(this).closest("form");
                const swalWithBootstrapButtons = Swal.mixin({
                    customClass: {
                        confirmButton: 'btn btn-success',
                        cancelButton: 'btn btn-danger'
                    },
                    buttonsStyling: false
                })
                swalWithBootstrapButtons.fire({
                    title: 'Are you sure?',
                    text: "This action can not be undone. Do you want to continue?",
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonText: 'Yes',
                    cancelButtonText: 'No',
                    reverseButtons: true
                }).then((result) => {
                    if (result.isConfirmed) {
                        form.submit();
                    }
                })
            });
        });
    </script> -->

  

resources/views/partials/admin/header.blade.php
@php
    $logo=\App\Models\Utility::get_file('uploads/logo/');
    $company_favicon=Utility::getValByName('company_favicon');
@endphp

<head>
    <title>@yield('page-title') - @if(Auth::user()->type == 'super admin')  {{config('app.name', 'vCard SaaS')}} @else {{(Utility::getValByName('title_text')) ? Utility::getValByName('title_text') : config('app.name', 'vCard SaaS')}} @endif</title>
    <!-- HTML5 Shim and Respond.js IE11 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 11]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- Meta -->
    <meta charset="utf-8"  />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="description" content="Dashboard Template Description" />
    <meta name="keywords" content="Dashboard Template" />
    <meta name="author" content="Rajodiya Infotech" />

    <!-- Favicon icon -->
    @if(Auth::user()->type == 'super admin')
        <link rel="icon" href="{{$logo.'/favicon.png'}}" type="image" sizes="16x16">
    @else
        <link rel="icon" href="{{ $logo . (isset($company_favicon) && !empty($company_favicon) ? $company_favicon : 'favicon.png') }}" type="image" sizes="16x16">
    @endif

    <!-- font css -->
    <link rel="stylesheet" href="{{ asset('assets/css/plugins/style.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/plugins/main.css')}}">
    <link rel="stylesheet" href="{{asset('assets/css/plugins/animate.min.css')}}" />
    <link rel="stylesheet" href="{{ asset('assets/fonts/tabler-icons.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/fonts/feather.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/fonts/fontawesome.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/fonts/material.css') }}">
    <link rel="stylesheet" href="{{asset('custom/libs/summernote/summernote-bs4.css')}}">
     @stack('css-page')
  
    
    <!-- vendor css -->
    @if ($setting['SITE_RTL'] == 'on')
        <link rel="stylesheet" href="{{ asset('assets/css/style-rtl.css') }}">
    @endif
    @if( isset($setting['cust_darklayout']) && $setting['cust_darklayout'] == 'on')
        <link rel="stylesheet" href="{{ asset('assets/css/style-dark.css') }}">
    @else
        <link rel="stylesheet" href="{{ asset('assets/css/style.css') }}">
    @endif

    <link rel="stylesheet" href="{{ asset('assets/css/customizer.css') }}">
    <link rel="stylesheet" href="{{ asset('custom/css/emojionearea.min.css') }}">
    <link rel="stylesheet" href="{{ asset('custom/css/custom.css') }}">
    <link rel="stylesheet" href="{{asset('assets/css/plugins/bootstrap-switch-button.min.css')}}">
</head>

resources/views/partials/admin/sidemenu.blade.php
@php
    // $logo=asset(Storage::url(''));
    $company_logo = \App\Models\Utility::GetLogo();
    $logo=\App\Models\Utility::get_file('uploads/logo/');
    // dd($company_logo);
@endphp


<!-- [ navigation menu ] start -->

@if (isset($setting['cust_theme_bg']) && $setting['cust_theme_bg'] == 'on')
    <nav class="dash-sidebar light-sidebar transprent-bg">
@else
    <nav class="dash-sidebar light-sidebar">
@endif
{{-- <nav class="dash-sidebar light-sidebar {{($layout_setting['cust_theme_bg'] == 'off' &&  $layout_setting['SITE_RTL'] != 'on') ? '' : 'transprent-bg'}}"> --}}
    <div class="navbar-wrapper">
        <div class="m-header main-logo">
            <a href="index.html" class="b-brand">
                <!-- ========   change your logo hear   ============ -->
                {{-- @if(Auth::user()->type == 'super admin') --}}
                    {{-- <img src="{{$logo.'/'.$company_logo}}" class="logo logo-lg" alt="..."> --}}
                    {{-- <img src="{{ $logo . (isset($company_logo) && !empty($company_logo) ? $company_logo : 'logo-dark.png') }}"
                alt="{{ config('app.name', 'AccountGo') }}" class="logo logo-lg"> --}}
                {{-- <img id="dark-logo" alt="your image" src="{{$logo.'logo-dark.png'}}" width="150px" class="big-logo">
                @else
                    {{-- <img src="{{asset(Storage::url($company_logo))}}" class="logo logo-lg" alt="...">
                    <img src="{{ $logo . (isset($company_logo) && !empty($company_logo) ? $company_logo : 'logo-dark.png') }}"
                alt="{{ config('app.name', 'AccountGo') }}" class="logo logo-lg">
                @endif --}}
                <!--  <img src="{{ asset('assets/images/logo-light.png') }}" alt="" class="logo logo-lg" /> -->
                <!-- <img src="{{ asset('assets/images/logo-dark.svg') }}" alt="" class="logo logo-sm" /> -->
                  <img src="{{ $logo . (isset($company_logo) && !empty($company_logo) ? $company_logo : 'logo-dark.png') }}"
                alt="{{ config('app.name', 'AccountGo') }}" class="logo logo-lg">
            </a>
        </div>
        <div class="navbar-content">
            <ul class="dash-navbar">
                <li class="dash-item {{ (Request::segment(1) == 'home' || Request::segment(1) == '' ||Request::segment(1) == 'dashboard')?'active':''}}">
                    <a href="{{route('home')}}" class="dash-link"><span class="dash-micon"><i
                                class="ti ti-home"></i></span><span class="dash-mtext">{{ __('Dashboard') }}</span></a>

                </li>
                @if(Auth::user()->type =='company')
                <li class="dash-item {{ (Request::segment(1) == 'business')?'active':''}}">
                    <a href="{{route('business.index')}}" class="dash-link"><span class="dash-micon"><i
                                class="ti ti-credit-card"></i></span><span class="dash-mtext">{{ __('Business') }}</span></a>

                </li>
                <li class="dash-item {{ (Request::segment(1) == 'appointments')?'active':''}}">
                    <a href="{{route('appointments.index')}}" class="dash-link"><span class="dash-micon"><i
                                class="ti ti-calendar-time"></i></span><span class="dash-mtext">{{ __('Appointments') }}</span></a>

                </li>
                <li class="dash-item {{ (Request::segment(1) == 'contacts')?'active':''}}">
                    <a href="{{route('contacts.index')}}" class="dash-link"><span class="dash-micon"><i
                                class="ti ti-phone"></i></span><span class="dash-mtext">{{ __('Contacts') }}</span></a>

                </li>
                <li class="dash-item {{ (Request::segment(1) == 'appointment-calendar')?'active':''}}">
                    <a href="{{route('appointment.calendar')}}" class="dash-link"><span class="dash-micon"><i
                                class="ti ti-calendar"></i></span><span class="dash-mtext">{{ __('Calendar') }}</span></a>

                </li>
                @endif
                @if(Auth::user()->type == 'super admin')
                    <li class="dash-item {{ (Request::segment(1) == 'users')?'active':''}}">
                    <a href="{{ route('users.index') }}" class="dash-link"><span class="dash-micon"><i
                                class="ti ti-user"></i></span><span class="dash-mtext">{{ __('Users') }}</span></a>

                    </li>
                @endif
                    {{-- <li class="dash-item {{ (Request::segment(1) == 'plans')?'active':''}}"> --}}
                    <li class="dash-item {{ (\Request::route()->getName() == 'plans') || (\Request::route()->getName() == 'stripe') ?'active':''}}">
                    <a href="{{ route('plans.index') }}" class="dash-link"><span class="dash-micon"><i
                                class="ti ti-award "></i></span><span class="dash-mtext">{{ __('Plans') }}</span></a>

                    </li>
                @if(Auth::user()->type == 'super admin')
                    <li class="dash-item {{ (Request::route()->getName() == 'plan_request.index') ? 'active' : '' }}">
                    <a href="{{ route('plan_request.index') }}" class="dash-link"><span class="dash-micon"><i
                                class="ti ti-brand-telegram"></i></span><span class="dash-mtext">{{__('Plan Request')}}</span></a>

                    </li>
                    <li class="dash-item {{ (Request::segment(1) == 'coupons')?'active':''}}">
                    <a href="{{ route('coupons.index') }}" class="dash-link"><span class="dash-micon"><i
                                class="ti ti-gift"></i></span><span class="dash-mtext">{{ __('Coupons') }}</span></a>

                    </li>

                    <li class="dash-item {{ (Request::segment(1) == 'order')?'active':''}}">
                    <a href="{{ route('order.index') }}" class="dash-link"><span class="dash-micon"><i
                                class="ti ti-shopping-cart"></i></span><span class="dash-mtext">{{__('Order')}}</span></a>

                    </li>
                    <li class="dash-item {{ (Request::segment(1) == 'email_template_lang')?'active':''}}">
                        <a href="{{route('manage.email.language',\Auth::user()->lang)}}" class="dash-link"><span class="dash-micon"><i
                                    class="ti ti-mail"></i></span><span class="dash-mtext">{{ __('Email Template') }}</span></a>

                        </li>
                @endif


                <li class="dash-item {{ (Request::segment(1) == 'systems')?'active':''}}">
                    <a href="{{route('systems.index')}}" class="dash-link"><span class="dash-micon"><i
                                class="ti ti-settings"></i></span><span class="dash-mtext">{{ __('Setting') }}</span></a>

                    </li>
            <!-- </li> -->




            </ul>
        </div>
    </div>
</nav>
<!-- [ navigation menu ] end -->