routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

require __DIR__.'/auth.php';

Route::get('/', ['as' => 'home', 'uses' => 'HomeController@landingPage'])->middleware(['XSS']);
Route::get('/home', ['as' => 'home', 'uses' => 'HomeController@index'])->middleware(['auth', 'XSS', 'CheckPlan']);
Route::get('/dashboard', ['as' => 'home', 'uses' => 'HomeController@index'])->middleware(['auth', 'XSS', 'CheckPlan']);
Route::get('/appointment-calendar/{id?}', ['as' => 'appointment.calendar', 'uses' => 'AppointmentDeatailController@getCalenderAllData'])->middleware(['auth', 'XSS']);

Route::get('/appointment-note/{id?}', ['as' => 'appointment.add-note', 'uses' => 'AppointmentDeatailController@add_note'])->middleware(['auth', 'XSS']);
Route::post('/appointment-note-store/{id?}', ['as' => 'appointment.note.store', 'uses' => 'AppointmentDeatailController@note_store'])->middleware(['auth', 'XSS']);

Route::get('get-appointment-detail/{id}', ['as' => 'appointment.details', 'uses' => 'AppointmentDeatailController@getAppointmentDetails'])->middleware(['auth', 'XSS']);
Route::resource('business', 'BusinessController')->middleware(['auth', 'XSS', 'CheckPlan']);
Route::group(['middleware' => ['auth', 'XSS', 'CheckPlan']], function () {
    Route::get('business/edit/{id}', ['as' => 'business.edit', 'uses' => 'BusinessController@edit']);
    Route::get('business/theme-edit/{id}', ['as' => 'business.edit2', 'uses' => 'BusinessController@edit2']);
    Route::get('business/analytics/{id}', ['as' => 'business.analytics', 'uses' => 'BusinessController@analytics']);
    Route::post('business/edit-theme/{id}', ['as' => 'business.edit-theme', 'uses' => 'BusinessController@editTheme']);
    Route::post('business/domain-setting/{id}', ['as' => 'business.domain-setting', 'uses' => 'BusinessController@domainsetting']);
    Route::resource('appointments', 'AppointmentDeatailController');
    // Route::get('appoinments/', ['as' => 'appointments.index', 'uses' => 'AppointmentDeatailController@index']);
    Route::resource('users', 'UserController');
    Route::get('user/{id}/plan', 'UserController@upgradePlan')->name('plan.upgrade');
    Route::get('user/{id}/plan/{pid}', 'UserController@activePlan')->name('plan.active');
    Route::get('business/preview/card/{slug}', ['as' => 'business.template', 'uses' => 'BusinessController@getcard']);
    Route::delete('business/destroy/{id}', ['as' => 'business.destroy', 'uses' => 'BusinessController@destroy']);
    Route::get('profile', 'UserController@profile')->name('profile');
    Route::post('edit-profile', 'UserController@editprofile')->name('update.account');
    Route::resource('systems', 'SystemController');
    Route::post('email-settings', 'SystemController@saveEmailSettings')->name('email.settings');
    Route::post('company-settings-store', 'SystemController@storeCompanySetting')->name('company.settings.store');

    Route::post('test-mail', 'SystemController@testMail')->name('test.mail')->middleware(['auth', 'XSS']);
    Route::post('test-mail/send', 'SystemController@testSendMail')->name('test.send.mail')->middleware(['auth', 'XSS']);

    // Route::post('/test',['as' => 'test.email','uses' =>'SettingsController@testEmail'])->middleware(['auth','XSS']);
    // Route::post('/test/send',['as' => 'test.email.send','uses' =>'SettingsController@testEmailSend'])->middleware(['auth','XSS']);

    Route::get('change-language/{lang}', 'UserController@changeLanquage')->name('change.language');
    Route::get('manage-language/{lang}', 'LanguageController@manageLanguage')->name('manage.language');
    Route::post('store-language-data/{lang}', 'LanguageController@storeLanguageData')->name('store.language.data');
    Route::get('create-language', 'LanguageController@createLanguage')->name('create.language');
    Route::post('store-language', 'LanguageController@storeLanguage')->name('store.language');

    Route::delete('/lang/{lang}', 'LanguageController@destroyLang')->name('lang.destroy');
    Route::resource('coupons', 'CouponController');
});

Route::post('stripe-settings', 'SystemController@savePaymentSettings')->name('payment.settings')->middleware(['auth', 'XSS']);
Route::get('/stripe/{code}', 'StripePaymentController@stripe')->name('stripe')->middleware(['auth', 'XSS']);
Route::post('/stripe', 'StripePaymentController@stripePost')->name('stripe.post')->middleware(['auth', 'XSS']);
Route::get('order', 'StripePaymentController@index')->name('order.index')->middleware(['auth', 'XSS']);
Route::any('/plan/error/{flag}', 'PaymentWallPaymentController@paymenterror')->name('callback.error');
Route::any('plan-mercado-callback/{plan_id}', 'MercadoPaymentController@mercadopagoPaymentCallback')->name('plan.mercado.callback')->middleware(['auth']);
Route::resource('plans', 'PlanController');
//================================= Custom Landing Page ====================================//

Route::get('/{slug}', 'BusinessController@getcard');
Route::post('appoinment/make-appointment', ['as' => 'appoinment.store', 'uses' => 'AppointmentDeatailController@store'])->middleware('XSS');

Route::post('change-password', 'UserController@updatePassword')->name('update.password');
Route::get('/download/{slug}', 'BusinessController@getVcardDownload')->name('bussiness.save');

Route::get('/apply-coupon', ['as' => 'apply.coupon', 'uses' => 'CouponController@applyCoupon'])->middleware(['auth', 'XSS']);

Route::post('prepare-payment', ['as' => 'prepare.payment', 'uses' => 'PlanController@preparePayment'])->middleware(['auth', 'XSS']);
Route::get('/payment/{code}', ['as' => 'payment', 'uses' => 'PlanController@payment'])->middleware(['auth', 'XSS']);

Route::post('plan-pay-with-paypal', 'PaypalController@planPayWithPaypal')->name('plan.pay.with.paypal')->middleware(['auth', 'XSS']);

//================================= Plan Payment Gateways  ====================================//

Route::post('/plan-pay-with-paystack', ['as' => 'plan.pay.with.paystack', 'uses' => 'PaystackPaymentController@planPayWithPaystack'])->middleware(['auth', 'XSS']);
Route::get('/plan/paystack/{pay_id}/{plan_id}', ['as' => 'plan.paystack', 'uses' => 'PaystackPaymentController@getPaymentStatus']);

Route::post('/plan-pay-with-flaterwave', ['as' => 'plan.pay.with.flaterwave', 'uses' => 'FlutterwavePaymentController@planPayWithFlutterwave'])->middleware(['auth', 'XSS']);
Route::get('/plan/flaterwave/{txref}/{plan_id}', ['as' => 'plan.flaterwave', 'uses' => 'FlutterwavePaymentController@getPaymentStatus']);

Route::post('/plan-pay-with-razorpay', ['as' => 'plan.pay.with.razorpay', 'uses' => 'RazorpayPaymentController@planPayWithRazorpay'])->middleware(['auth', 'XSS']);
Route::get('/plan/razorpay/{txref}/{plan_id}', ['as' => 'plan.razorpay', 'uses' => 'RazorpayPaymentController@getPaymentStatus']);

Route::post('/plan-pay-with-paytm', ['as' => 'plan.pay.with.paytm', 'uses' => 'PaytmPaymentController@planPayWithPaytm'])->middleware(['auth', 'XSS']);
Route::post('/plan/paytm/{plan}', ['as' => 'plan.paytm', 'uses' => 'PaytmPaymentController@getPaymentStatus']);

Route::post('/plan-pay-with-mercado', ['as' => 'plan.pay.with.mercado', 'uses' => 'MercadoPaymentController@planPayWithMercado'])->middleware(['auth', 'XSS']);
Route::post('/plan/mercado', ['as' => 'plan.mercado', 'uses' => 'MercadoPaymentController@getPaymentStatus']);

Route::post('/plan-pay-with-mollie', ['as' => 'plan.pay.with.mollie', 'uses' => 'MolliePaymentController@planPayWithMollie'])->middleware(['auth', 'XSS']);
Route::get('/plan/mollie/{plan}', ['as' => 'plan.mollie', 'uses' => 'MolliePaymentController@getPaymentStatus']);

Route::post('/plan-pay-with-skrill', ['as' => 'plan.pay.with.skrill', 'uses' => 'SkrillPaymentController@planPayWithSkrill'])->middleware(['auth', 'XSS']);
Route::get('/plan/skrill/{plan}', ['as' => 'plan.skrill', 'uses' => 'SkrillPaymentController@getPaymentStatus']);

Route::post('/plan-pay-with-coingate', ['as' => 'plan.pay.with.coingate', 'uses' => 'CoingatePaymentController@planPayWithCoingate'])->middleware(['auth', 'XSS']);
Route::get('/plan/coingate/{plan}', ['as' => 'plan.coingate', 'uses' => 'CoingatePaymentController@getPaymentStatus']);

Route::get('{id}/plan-get-payment-status', 'PaypalController@planGetPaymentStatus')->name('plan.get.payment.status')->middleware(
    [
        'auth',
        'XSS',
    ]
);

Route::get('business/{slug}/get_card', 'BusinessController@cardpdf')->name('get.card');
Route::get('businessqr/download/', 'BusinessController@downloadqr')->name('download.qr');

// Route::get('business/card', 'BusinessController@card')->name('get.card');

Route::post('business/block-setting/{id}', ['as' => 'business.block-setting', 'uses' => 'BusinessController@blocksetting'])->middleware(
    [
        'auth',
        'XSS',
    ]
);

//=================================Plan Request Module ====================================//
Route::get('plan_request/index', 'PlanRequestController@index')->name('plan_request.index')->middleware(['auth', 'XSS']);
Route::get('request_frequency/{id}', 'PlanRequestController@requestView')->name('request.view')->middleware(['auth', 'XSS']);
Route::get('request_send/{id}', 'PlanRequestController@userRequest')->name('send.request')->middleware(['auth', 'XSS']);
Route::get('request_response/{id}/{response}', 'PlanRequestController@acceptRequest')->name('response.request')->middleware(['auth', 'XSS']);
Route::get('request_cancel/{id}', 'PlanRequestController@cancelRequest')->name('request.cancel')->middleware(['auth', 'XSS']);

/*==================================Recaptcha====================================================*/

resources/views/user/create.blade.php
{{Form::open(array('url'=>'users','method'=>'post'))}}
<div class="row">
    <div class="col-md-6">
        <div class="form-group">
            {{Form::label('name',__('Name'),['class'=>'form-label']) }}
            {{Form::text('name',null,array('class'=>'form-control','placeholder'=>__('Enter User Name'),'required'=>'required'))}}
            @error('name')
            <small class="invalid-name" role="alert">
                <strong class="text-danger">{{ $message }}</strong>
            </small>
            @enderror
        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            {{Form::label('email',__('Email'),['class'=>'form-label'])}}
            {{Form::text('email',null,array('class'=>'form-control','placeholder'=>__('Enter User Email'),'required'=>'required'))}}
            @error('email')
            <small class="invalid-email" role="alert">
                <strong class="text-danger">{{ $message }}</strong>
            </small>
            @enderror
        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            {{Form::label('password',__('Password'),['class'=>'form-label'])}}
            {{Form::password('password',array('class'=>'form-control','placeholder'=>__('Enter User Password'),'required'=>'required','minlength'=>"6"))}}
            @error('password')
            <small class="invalid-password" role="alert">
                <strong class="text-danger">{{ $message }}</strong>
            </small>
            @enderror
        </div>
    </div>
    @if(\Auth::user()->type != 'super admin')
        <div class="form-group col-md-6">
            {{ Form::label('role', __('User Role'),['class'=>'form-label']) }}
            {!! Form::select('role', $roles, null,array('class' => 'form-control select2','required'=>'required')) !!}
            @error('role')
            <small class="invalid-role" role="alert">
                <strong class="text-danger">{{ $message }}</strong>
            </small>
            @enderror
        </div>
    @endif
</div>
<div class="modal-footer p-0 pt-3">
    <button type="button" class="btn btn-secondary btn-light" data-bs-dismiss="modal">{{ __('Cancel') }}</button>
    <input class="btn btn-primary" type="submit" value="{{ __('Create') }}">
</div>
{{Form::close()}}

resources/views/user/edit.blade.php
{{Form::model($user,array('route' => array('users.update', $user->id), 'method' => 'PUT')) }}
<div class="row">
    <div class="col-md-6">
        <div class="form-group ">
            {{Form::label('name',__('Name'),['class'=>'form-label']) }}
            {{Form::text('name',null,array('class'=>'form-control font-style','placeholder'=>__('Enter User Name')))}}
            @error('name')
            <small class="invalid-name" role="alert">
                <strong class="text-danger">{{ $message }}</strong>
            </small>
            @enderror
        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            {{Form::label('email',__('Email'),['class'=>'form-label'])}}
            {{Form::text('email',null,array('class'=>'form-control','placeholder'=>__('Enter User Email')))}}
            @error('email')
            <small class="invalid-email" role="alert">
                <strong class="text-danger">{{ $message }}</strong>
            </small>
            @enderror
        </div>
    </div>
    @if(\Auth::user()->type != 'super admin')
        <div class="form-group col-md-12">
            {{ Form::label('role', __('User Role'),['class'=>'form-label']) }}
            {!! Form::select('role', $roles, $user->roles,array('class' => 'form-control select2','required'=>'required')) !!}
            @error('role')
            <small class="invalid-role" role="alert">
                <strong class="text-danger">{{ $message }}</strong>
            </small>
            @enderror
        </div>
    @endif
</div>
 <div class="modal-footer p-0 pt-3">
    <button type="button" class="btn btn-secondary btn-light" data-bs-dismiss="modal">{{ __('Cancel') }}</button>
    <input class="btn btn-primary" type="submit" value="{{ __('Update') }}">
</div>
{{Form::close()}}

resources/views/user/index.blade.php
@extends('layouts.admin')
@php
    // $profile=asset(Storage::url('uploads/avatar/'));
    $profile=\App\Models\Utility::get_file('uploads/avatar/');
@endphp
@section('page-title')
   {{__('Manage Users')}}
@endsection
@section('title')
   {{__('Manage Users')}}
@endsection
@section('action-btn')
<div class="col-xl-8 col-lg-8 col-md-8 d-flex align-items-center justify-content-between justify-content-md-end" data-bs-placement="top" data-bs-toggle="tooltip"
            data-bs-original-title="{{__('Create New User')}}">
    <a href="#" class="btn btn-sm btn-primary btn-icon m-1" data-bs-toggle="modal"
        data-bs-target="#exampleModal" data-url="{{ route('users.create') }}"
        data-bs-whatever="{{__('Create New User')}}" data-toggle="tooltip"
        data-bs-title="{{__('Create New User')}}"> <span class="text-white"> 
            <i class="ti ti-plus text-white" ></i></span>
    </a>
</div>
@endsection
@section('breadcrumb')
    <li class="breadcrumb-item active" aria-current="page">{{__('User')}}</li>
@endsection
@section('content')

<div class="row">
    @foreach ($users as $user)
        <div class="col-xl-3">
            <div class="card text-center">
               <div class="d-flex justify-content-between align-items-center px-3 pt-3">
                    <div class="border-0 pb-0 ">
                        <h6 class="mb-0">
                            <div class="badge p-2 px-3 rounded bg-primary">{{ ucfirst($user->type) }}</div>
                        </h6>
                    </div>
                    <div class="card-header-right">
                        <div class="btn-group card-option">
                            <button type="button" class="btn"
                                data-bs-toggle="dropdown" aria-haspopup="true"
                                aria-expanded="false">
                                <i class="feather icon-more-vertical"></i>
                            </button>
                            <div class="dropdown-menu dropdown-menu-end">
                                    <a href="#" class="dropdown-item" data-url="{{ route('users.edit',$user->id) }}" data-ajax-popup="true" data-title="{{__('Update User')}}"><i class="ti ti-edit mr-1"></i><span class="ml-2">{{__('Edit')}}</span></a>

                                   <a href="#" class="dropdown-item" data-ajax-popup="true" data-title="{{__('Reset Password')}}" data-url="{{route('user.reset',\Crypt::encrypt($user->id))}}"><i class="ti ti-key"></i>
                                     <span class="ml-2">{{__('Reset Password')}}</span></a>  
                                    <a href="#" class="bs-pass-para dropdown-item"  data-confirm="{{__('Are You Sure?')}}" data-text="{{__('This action can not be undone. Do you want to continue?')}}" data-confirm-yes="delete-form-{{$user->id}}" title="{{__('Delete')}}" data-bs-toggle="tooltip" data-bs-placement="top"><i class="ti ti-trash"></i><span class="ml-2">{{__('Delete')}}</span></a>
                                        {!! Form::open(['method' => 'DELETE', 'route' => ['users.destroy', $user->id],'id'=>'delete-form-'.$user->id]) !!}
                                        {!! Form::close() !!} 
                            </div>
                        </div>
                    </div>
               </div>
                <div class="card-body">
                    <div class="avatar">
                        <a href="{{(!empty($user->avatar))? asset(Storage::url('uploads/avatar/'.$user->avatar)): asset(Storage::url("uploads/avatar/avatar.png"))}}" target="_blank">
                             <img src="{{(!empty($user->avatar))? asset(Storage::url('uploads/avatar/'.$user->avatar)): asset(Storage::url("uploads/avatar/avatar.png"))}}" class="rounded-circle img_users_fix_size">
                        </a>
                    </div>
                    <h4 class="mt-2">{{ $user->name }}</h4>
                    <small>{{ $user->email }}</small>
                    @if(\Auth::user()->type == 'super admin')
                    <div class=" mb-0 mt-3">
                        <div class=" p-3">
                            <div class="row">
                                   <div class="col-5 text-start">
                                        <h6 class="mb-0  mt-1">{{!empty($user->currentPlan)?$user->currentPlan->name:''}}</h6>
                                    </div>
                                     <div class="col-7 text-end">
                                        <a href="#" data-url="{{ route('plan.upgrade',$user->id) }}" class="btn btn-sm btn-primary btn-icon" data-size="lg" data-ajax-popup="true" data-title="{{__('Upgrade Plan')}}">{{__('Upgrade Plan')}}</a>  
                                    </div>
                                   <!--  <div class="col-6 {{Auth::user()->type == 'admin' ? 'text-end' : 'text-start' }}  ">
                                        <h6 class="mb-0 px-3">{{__('Plan Expired : ') }} {{!empty($user->plan_expire_date) ? \Auth::user()->dateFormat($user->plan_expire_date): __('Unlimited')}}</h6>
                                    </div> -->
                                    <div class="col-6 text-start mt-4">
                                        <h6 class="mb-0 px-3">{{$user->totalBusiness($user->id)}}</h6>
                                        <p class="text-muted text-sm mb-0">{{__('Business')}}</p>
                                    </div>

                                <div class="col-6 text-end mt-4">
                                    <h6 class="mb-0 px-3">{{$user->getTotalAppoinments()}}</h6>
                                    <p class="text-muted text-sm mb-0">{{__('Appointments')}}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <p class="mt-2 mb-0">
                    
                        <button class="btn btn-sm btn-neutral mt-3 font-weight-500">
                            <a>{{__('Plan Expired : ') }} {{!empty($user->plan_expire_date) ? \Auth::user()->dateFormat($user->plan_expire_date): __('Unlimited')}}</a>
                        </button>
                    
                    </p>
                    @endif
                </div>
            </div>
        </div>
    @endforeach
    <div class="col-md-3">
        <a href="#" class="btn-addnew-project"  data-ajax-popup="true" data-size="md" data-title="{{ __('Create New User') }}" data-url="{{ route('users.create') }}">
            <div class="badge bg-primary proj-add-icon">
                <i class="ti ti-plus"></i>
            </div>
            <h6 class="mt-4 mb-2">{{ __('New User') }}</h6>
            <p class="text-muted text-center">{{ __('Click here to add New User') }}</p>
        </a>
    </div>
</div>
@endsection

resources/views/user/plan.blade.php
<div class="table-responsive">
    <table class="table ">
        <tbody>
        @foreach($plans as $plan)
            <tr>
                <td>
                    <div class="font-style font-weight-bold">{{$plan->name}} ({{(env('CURRENCY_SYMBOL')) ? env('CURRENCY_SYMBOL') : '$'}}{{$plan->price}}) {{' / '. $plan->duration}}</div>
                </td>
                <td>{{ __('Business') }} : {{ $plan->business }}</td>
                <td>
                    @if($user->plan==$plan->id)
                        <button type="button" class="btn btn-xs btn-soft-success btn-icon">
                            <span class="btn-inner--icon"><i class="fas fa-check"></i></span>
                            <span class="btn-inner--text">{{__('Active')}}</span>
                        </button>
                    @else
                        <div>
                            <a href="{{route('plan.active',[$user->id,$plan->id])}}" class="btn btn-sm btn-primary btn-icon" title="{{ __('Click to Upgrade Plan') }}"><i class="ti ti-shopping-cart"></i> {{ __('Upgrade') }}</a>
                        </div>
                    @endif
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>

resources/views/user/profile.blade.php
@extends('layouts.admin')
@php
    // $profile=asset(Storage::url('uploads/avatar/'));
    $profile=\App\Models\Utility::get_file('uploads/avatar/');
    // $profile=asset(Storage::url('uploads/avatar/'));
    $users = \Auth::user();
@endphp
@section('page-title')
    {{__('Profile Account')}}
@endsection
@push('custom-scripts')
<script>
    var scrollSpy = new bootstrap.ScrollSpy(document.body, {
        target: '#useradd-sidenav',
        offset: 300
    })
</script>
@endpush
@section('breadcrumb')
    <li class="breadcrumb-item active" aria-current="page">{{__('Profile')}}</li>
@endsection
@section('content')
    <div class="row">
    <!-- [ sample-page ] start -->
<div class="col-sm-12">
    <div class="row">
        <div class="col-xl-3">
            <div class="card sticky-top" style="top:30px">
                <div class="list-group list-group-flush" id="useradd-sidenav">
                    <a href="#useradd-2" class="list-group-item list-group-item-action border-0 ">{{__('Personal info')}}
                        <div class="float-end"><i class="ti ti-chevron-right"></i></div></a>
                    <a href="#useradd-3" class="list-group-item list-group-item-action border-0">{{__('Change Password')}}
                        <div class="float-end"><i class="ti ti-chevron-right"></i></div></a>   
                </div>
            </div>
        </div>
        <div class="col-xl-9">
            <div id="useradd-2" class="card">
                <div class="card-header">
                    <h5>{{__('Personal info')}}</h5>
                    <small class="text-muted">{{ __('Edit details about your Password') }}</small>
                </div>
                {{Form::model($userDetail,array('route' => array('update.account'), 'method' => 'post', 'enctype' => "multipart/form-data"))}}
                <div class="card-body pb-0">
                                
                                <div class="row">
                                    <div class="col-lg-6 col-sm-6">
                                        <div class="form-group">
                                            {{Form::label('name',__('Name'),array('class'=>'form-label'))}}
                                            {{Form::text('name',null,array('class'=>'form-control font-style','placeholder'=>__('Enter User Name')))}}
                                            @error('name')
                                            <span class="invalid-name" role="alert">
                                                    <strong class="text-danger">{{ $message }}</strong>
                                                </span>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="col-lg-6 col-sm-6">
                                        <div class="form-group">
                                            {{Form::label('email',__('Email'),array('class'=>'form-label'))}}
                                            {{Form::text('email',null,array('class'=>'form-control','placeholder'=>__('Enter User Email')))}}
                                            @error('email')
                                            <span class="invalid-email" role="alert">
                                                <strong class="text-danger">{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>
                                    </div>
                                    

                                    <div class="col-lg-6 col-md-6 mb-0 mt-2">
                                            <div class="choose-files">
                                                <label for="avatar">
                                                    <div class=" bg-primary company_logo_update"> <i
                                                            class="ti ti-upload px-1"></i>{{ __('Choose file here') }}</div>
                                                    <input type="file" class="form-control file" id="avatar" name="profile" data-filename="profiles" onchange="document.getElementById('blah').src = window.URL.createObjectURL(this.files[0])">
                                                </label>
                                                
                                            </div>
                                            <img src="{{ !empty($users->avatar) ? $profile . '/' . $users->avatar : $profile . '/avatar.png' }}" id="blah" width="25%"/>
                                            <span class="profiles"></span>
                                    </div>

                                </div>

                                
                </div>
                <div class="card-footer">
                    <div class="text-end">
                        {{Form::submit(__('Save Change'),array('class'=>'btn btn-print-invoice btn-primary m-r-10'))}}
                    </div>
                    
                </div>
                {{Form::close()}}
                
            </div>

            <div id="useradd-3" class="card">
                <div class="card-header">
                    <h5>{{__('Change Password')}}</h5>
                    <small class="text-muted">{{ __('Edit details about your Password') }}</small>
                </div>
                {{Form::model($userDetail,array('route' => array('update.password',$userDetail->id), 'method' => 'post'))}}
                <div class="card-body">
                    <div class="row">
                                    <div class="col-lg-6 col-sm-6">
                                        <div class="form-group">
                                            {{Form::label('current_password',__('Current Password'),array('class'=>'form-label'))}}
                                            {{Form::password('current_password',array('class'=>'form-control','placeholder'=>__('Enter Current Password')))}}
                                            @error('current_password')
                                            <span class="invalid-current_password" role="alert">
                                                                    <strong class="text-danger">{{ $message }}</strong>
                                                                </span>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="col-lg-6 col-sm-6">
                                        <div class="form-group">
                                            {{Form::label('new_password',__('New Password'),array('class'=>'form-label'))}}
                                            {{Form::password('new_password',array('class'=>'form-control','placeholder'=>__('Enter New Password')))}}
                                            @error('new_password')
                                            <span class="invalid-new_password" role="alert">
                                                                <strong class="text-danger">{{ $message }}</strong>
                                                            </span>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            {{Form::label('confirm_password',__('Re-type New Password'),array('class'=>'form-label'))}}
                                            {{Form::password('confirm_password',array('class'=>'form-control','placeholder'=>__('Enter Re-type New Password')))}}
                                            @error('confirm_password')
                                            <span class="invalid-confirm_password" role="alert">
                                                                <strong class="text-danger">{{ $message }}</strong>
                                                            </span>
                                            @enderror
                                        </div>
                                    </div>
                                </div>
                </div>
                <div class="modal-footer">
                                {{Form::submit(__('Save Change'),array('class'=>'btn btn-print-invoice  btn-primary m-r-10'))}}
                            </div>
                 {{Form::close()}}
                    
                                
                               
            </div>
        </div>
    </div>
    <!-- [ sample-page ] end -->
</div>
    <!-- [ Main Content ] end -->
</div>
@endsection