routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

require __DIR__.'/auth.php';

Route::get('/', ['as' => 'home', 'uses' => 'HomeController@landingPage'])->middleware(['XSS']);
Route::get('/home', ['as' => 'home', 'uses' => 'HomeController@index'])->middleware(['auth', 'XSS', 'CheckPlan']);
Route::get('/dashboard', ['as' => 'home', 'uses' => 'HomeController@index'])->middleware(['auth', 'XSS', 'CheckPlan']);
Route::get('/appointment-calendar/{id?}', ['as' => 'appointment.calendar', 'uses' => 'AppointmentDeatailController@getCalenderAllData'])->middleware(['auth', 'XSS']);

Route::get('/appointment-note/{id?}', ['as' => 'appointment.add-note', 'uses' => 'AppointmentDeatailController@add_note'])->middleware(['auth', 'XSS']);
Route::post('/appointment-note-store/{id?}', ['as' => 'appointment.note.store', 'uses' => 'AppointmentDeatailController@note_store'])->middleware(['auth', 'XSS']);

Route::get('get-appointment-detail/{id}', ['as' => 'appointment.details', 'uses' => 'AppointmentDeatailController@getAppointmentDetails'])->middleware(['auth', 'XSS']);
Route::resource('business', 'BusinessController')->middleware(['auth', 'XSS', 'CheckPlan']);
Route::group(['middleware' => ['auth', 'XSS', 'CheckPlan']], function () {
    Route::get('business/edit/{id}', ['as' => 'business.edit', 'uses' => 'BusinessController@edit']);
    Route::get('business/theme-edit/{id}', ['as' => 'business.edit2', 'uses' => 'BusinessController@edit2']);
    Route::get('business/analytics/{id}', ['as' => 'business.analytics', 'uses' => 'BusinessController@analytics']);
    Route::post('business/edit-theme/{id}', ['as' => 'business.edit-theme', 'uses' => 'BusinessController@editTheme']);
    Route::post('business/domain-setting/{id}', ['as' => 'business.domain-setting', 'uses' => 'BusinessController@domainsetting']);
    Route::resource('appointments', 'AppointmentDeatailController');
    // Route::get('appoinments/', ['as' => 'appointments.index', 'uses' => 'AppointmentDeatailController@index']);
    Route::resource('users', 'UserController');
    Route::get('user/{id}/plan', 'UserController@upgradePlan')->name('plan.upgrade');
    Route::get('user/{id}/plan/{pid}', 'UserController@activePlan')->name('plan.active');
    Route::get('business/preview/card/{slug}', ['as' => 'business.template', 'uses' => 'BusinessController@getcard']);
    Route::delete('business/destroy/{id}', ['as' => 'business.destroy', 'uses' => 'BusinessController@destroy']);
    Route::get('profile', 'UserController@profile')->name('profile');
    Route::post('edit-profile', 'UserController@editprofile')->name('update.account');
    Route::resource('systems', 'SystemController');
    Route::post('email-settings', 'SystemController@saveEmailSettings')->name('email.settings');
    Route::post('company-settings-store', 'SystemController@storeCompanySetting')->name('company.settings.store');

    Route::post('test-mail', 'SystemController@testMail')->name('test.mail')->middleware(['auth', 'XSS']);
    Route::post('test-mail/send', 'SystemController@testSendMail')->name('test.send.mail')->middleware(['auth', 'XSS']);

    // Route::post('/test',['as' => 'test.email','uses' =>'SettingsController@testEmail'])->middleware(['auth','XSS']);
    // Route::post('/test/send',['as' => 'test.email.send','uses' =>'SettingsController@testEmailSend'])->middleware(['auth','XSS']);

    Route::get('change-language/{lang}', 'UserController@changeLanquage')->name('change.language');
    Route::get('manage-language/{lang}', 'LanguageController@manageLanguage')->name('manage.language');
    Route::post('store-language-data/{lang}', 'LanguageController@storeLanguageData')->name('store.language.data');
    Route::get('create-language', 'LanguageController@createLanguage')->name('create.language');
    Route::post('store-language', 'LanguageController@storeLanguage')->name('store.language');

    Route::delete('/lang/{lang}', 'LanguageController@destroyLang')->name('lang.destroy');
    Route::resource('coupons', 'CouponController');
});

Route::post('stripe-settings', 'SystemController@savePaymentSettings')->name('payment.settings')->middleware(['auth', 'XSS']);
Route::get('/stripe/{code}', 'StripePaymentController@stripe')->name('stripe')->middleware(['auth', 'XSS']);
Route::post('/stripe', 'StripePaymentController@stripePost')->name('stripe.post')->middleware(['auth', 'XSS']);
Route::get('order', 'StripePaymentController@index')->name('order.index')->middleware(['auth', 'XSS']);
Route::any('/plan/error/{flag}', 'PaymentWallPaymentController@paymenterror')->name('callback.error');
Route::any('plan-mercado-callback/{plan_id}', 'MercadoPaymentController@mercadopagoPaymentCallback')->name('plan.mercado.callback')->middleware(['auth']);
Route::resource('plans', 'PlanController');
//================================= Custom Landing Page ====================================//

Route::get('/{slug}', 'BusinessController@getcard');
Route::post('appoinment/make-appointment', ['as' => 'appoinment.store', 'uses' => 'AppointmentDeatailController@store'])->middleware('XSS');

Route::post('change-password', 'UserController@updatePassword')->name('update.password');
Route::get('/download/{slug}', 'BusinessController@getVcardDownload')->name('bussiness.save');

Route::get('/apply-coupon', ['as' => 'apply.coupon', 'uses' => 'CouponController@applyCoupon'])->middleware(['auth', 'XSS']);

Route::post('prepare-payment', ['as' => 'prepare.payment', 'uses' => 'PlanController@preparePayment'])->middleware(['auth', 'XSS']);
Route::get('/payment/{code}', ['as' => 'payment', 'uses' => 'PlanController@payment'])->middleware(['auth', 'XSS']);

Route::post('plan-pay-with-paypal', 'PaypalController@planPayWithPaypal')->name('plan.pay.with.paypal')->middleware(['auth', 'XSS']);

//================================= Plan Payment Gateways  ====================================//

Route::post('/plan-pay-with-paystack', ['as' => 'plan.pay.with.paystack', 'uses' => 'PaystackPaymentController@planPayWithPaystack'])->middleware(['auth', 'XSS']);
Route::get('/plan/paystack/{pay_id}/{plan_id}', ['as' => 'plan.paystack', 'uses' => 'PaystackPaymentController@getPaymentStatus']);

Route::post('/plan-pay-with-flaterwave', ['as' => 'plan.pay.with.flaterwave', 'uses' => 'FlutterwavePaymentController@planPayWithFlutterwave'])->middleware(['auth', 'XSS']);
Route::get('/plan/flaterwave/{txref}/{plan_id}', ['as' => 'plan.flaterwave', 'uses' => 'FlutterwavePaymentController@getPaymentStatus']);

Route::post('/plan-pay-with-razorpay', ['as' => 'plan.pay.with.razorpay', 'uses' => 'RazorpayPaymentController@planPayWithRazorpay'])->middleware(['auth', 'XSS']);
Route::get('/plan/razorpay/{txref}/{plan_id}', ['as' => 'plan.razorpay', 'uses' => 'RazorpayPaymentController@getPaymentStatus']);

Route::post('/plan-pay-with-paytm', ['as' => 'plan.pay.with.paytm', 'uses' => 'PaytmPaymentController@planPayWithPaytm'])->middleware(['auth', 'XSS']);
Route::post('/plan/paytm/{plan}', ['as' => 'plan.paytm', 'uses' => 'PaytmPaymentController@getPaymentStatus']);

Route::post('/plan-pay-with-mercado', ['as' => 'plan.pay.with.mercado', 'uses' => 'MercadoPaymentController@planPayWithMercado'])->middleware(['auth', 'XSS']);
Route::post('/plan/mercado', ['as' => 'plan.mercado', 'uses' => 'MercadoPaymentController@getPaymentStatus']);

Route::post('/plan-pay-with-mollie', ['as' => 'plan.pay.with.mollie', 'uses' => 'MolliePaymentController@planPayWithMollie'])->middleware(['auth', 'XSS']);
Route::get('/plan/mollie/{plan}', ['as' => 'plan.mollie', 'uses' => 'MolliePaymentController@getPaymentStatus']);

Route::post('/plan-pay-with-skrill', ['as' => 'plan.pay.with.skrill', 'uses' => 'SkrillPaymentController@planPayWithSkrill'])->middleware(['auth', 'XSS']);
Route::get('/plan/skrill/{plan}', ['as' => 'plan.skrill', 'uses' => 'SkrillPaymentController@getPaymentStatus']);

Route::post('/plan-pay-with-coingate', ['as' => 'plan.pay.with.coingate', 'uses' => 'CoingatePaymentController@planPayWithCoingate'])->middleware(['auth', 'XSS']);
Route::get('/plan/coingate/{plan}', ['as' => 'plan.coingate', 'uses' => 'CoingatePaymentController@getPaymentStatus']);

Route::get('{id}/plan-get-payment-status', 'PaypalController@planGetPaymentStatus')->name('plan.get.payment.status')->middleware(
    [
        'auth',
        'XSS',
    ]
);

Route::get('business/{slug}/get_card', 'BusinessController@cardpdf')->name('get.card');
Route::get('businessqr/download/', 'BusinessController@downloadqr')->name('download.qr');

// Route::get('business/card', 'BusinessController@card')->name('get.card');

Route::post('business/block-setting/{id}', ['as' => 'business.block-setting', 'uses' => 'BusinessController@blocksetting'])->middleware(
    [
        'auth',
        'XSS',
    ]
);

//=================================Plan Request Module ====================================//
Route::get('plan_request/index', 'PlanRequestController@index')->name('plan_request.index')->middleware(['auth', 'XSS']);
Route::get('request_frequency/{id}', 'PlanRequestController@requestView')->name('request.view')->middleware(['auth', 'XSS']);
Route::get('request_send/{id}', 'PlanRequestController@userRequest')->name('send.request')->middleware(['auth', 'XSS']);
Route::get('request_response/{id}/{response}', 'PlanRequestController@acceptRequest')->name('response.request')->middleware(['auth', 'XSS']);
Route::get('request_cancel/{id}', 'PlanRequestController@cancelRequest')->name('request.cancel')->middleware(['auth', 'XSS']);

/*==================================Recaptcha====================================================*/

app/Http/Controllers/PlanController.php
<?php

namespace App\Http\Controllers;

use App\Models\Plan;
use App\Models\Utility;
use Illuminate\Http\Request;

class PlanController extends Controller
{
    public function index()
    {
        // \App::setLocale(\Auth::user()->currentLanguage());
        $users = \Auth::user();
        $currantLang = $users->currentLanguage();
        $plans = Plan::get();
        $admin_payment_setting = Utility::getAdminPaymentSetting();
        // dd($admin_payment_setting);
        return view('plan.index', compact('plans', 'admin_payment_setting', 'currantLang', 'users'));
    }

    public function create()
    {
        $arrDuration = [
            'Unlimited' => __('Unlimited'),
            'Month' => __('Per Month'),
            'Year' => __('Per Year'),
        ];
        // dd($arrDuration);
        return view('plan.create', compact('arrDuration'));
    }

    public function store(Request $request)
    {
        $admin_payment_setting = Utility::getAdminPaymentSetting();

        if ($admin_payment_setting['is_stripe_enabled'] == 'on' || $admin_payment_setting['is_paypal_enabled'] == 'on' || $admin_payment_setting['is_paystack_enabled'] == 'on' || $admin_payment_setting['is_flutterwave_enabled'] == 'on' || $admin_payment_setting['is_razorpay_enabled'] == 'on' || $admin_payment_setting['is_mercado_enabled'] == 'on' || $admin_payment_setting['is_paytm_enabled'] == 'on' || $admin_payment_setting['is_mollie_enabled'] == 'on' || $admin_payment_setting['is_skrill_enabled'] == 'on' || $admin_payment_setting['is_coingate_enabled'] == 'on') {
            $post = $request->all();
            $validator = \Validator::make(
                $request->all(), [
                    'name' => 'required|unique:plans',
                    'duration' => 'required',
                    'price' => 'required',
                    'themes' => 'required',
                    'business' => 'required',
                ]
            );
            if ($validator->fails()) {
                $messages = $validator->getMessageBag();

                return redirect()->back()->with('error', $messages->first());
            }
            if ($request->has('themes')) {
                $post['themes'] = implode(',', $request->themes);
            }
            if (! isset($request->enable_custdomain)) {
                $post['enable_custdomain'] = 'off';
            }
            if (! isset($request->enable_custsubdomain)) {
                $post['enable_custsubdomain'] = 'off';
            }
            if (! isset($request->enable_branding)) {
                $post['enable_branding'] = 'off';
            }
            if (Plan::create($post)) {
                return redirect()->back()->with('success', __('Plan Successfully created.'));
            } else {
                return redirect()->back()->with('error', __('Something is wrong.'));
            }
        } else {
            return redirect()->back()->with('error', __('Please set stripe or paypal api key & secret key for add new plan.'));
        }
    }

        public function edit($plan_id)
        {
            $arrDuration = [
                'Unlimited' => __('Unlimited'),
                'Month' => __('Per Month'),
                'Year' => __('Per Year'),
            ];
            $plan = Plan::find($plan_id);

            return view('plan.edit', compact('plan', 'arrDuration'));
        }

    public function update(Request $request, $plan_id)
    {
        // $admin_payment_setting = Utility::getAdminPaymentSetting();
        $admin_payment_setting = Utility::paySettings();

        if (($admin_payment_setting['is_stripe_enabled'] == 'on' || $admin_payment_setting['is_paypal_enabled'] == 'on' || $admin_payment_setting['is_paystack_enabled'] == 'on' || $admin_payment_setting['is_flutterwave_enabled'] == 'on' || $admin_payment_setting['is_razorpay_enabled'] == 'on' || $admin_payment_setting['is_mercado_enabled'] == 'on' || $admin_payment_setting['is_paytm_enabled'] == 'on' || $admin_payment_setting['is_mollie_enabled'] == 'on' || $admin_payment_setting['is_skrill_enabled'] == 'on' || $admin_payment_setting['is_coingate_enabled'] == 'on') || $request->price <= 0) {
            $plan = Plan::find($plan_id);
            if (! empty($plan)) {
                $validator = \Validator::make(
                    $request->all(), [
                        'name' => 'required|unique:plans,name,'.$plan_id,
                        'duration' => 'required',
                        'price' => 'required',
                        'themes' => 'required',
                    ]
                );
                if ($validator->fails()) {
                    $messages = $validator->getMessageBag();

                    return redirect()->back()->with('error', $messages->first());
                }
                $post = $request->all();
                if ($request->has('themes')) {
                    $post['themes'] = implode(',', $request->themes);
                }
                if (! isset($request->enable_custdomain)) {
                    $post['enable_custdomain'] = 'off';
                }
                if (! isset($request->enable_custsubdomain)) {
                    $post['enable_custsubdomain'] = 'off';
                }
                if (! isset($request->enable_branding)) {
                    $post['enable_branding'] = 'off';
                }
                if ($plan->update($post)) {
                    return redirect()->back()->with('success', __('Plan successfully updated.'));
                } else {
                    return redirect()->back()->with('error', __('Something is wrong.'));
                }
            } else {
                return redirect()->back()->with('error', __('Plan not found.'));
            }
        } else {
            return redirect()->back()->with('error', __('Please set stripe api key & secret key for add new plan.'));
        }
    }

    public function userPlan(Request $request)
    {
        $objUser = \Auth::user();
        // dd($objUser);
        $planID = \Illuminate\Support\Facades\Crypt::decrypt($request->code);
        $plan = Plan::find($planID);

        if ($plan) {
            if ($plan->price <= 0) {
                $objUser->assignPlan($plan->id);

                return redirect()->route('plans.index')->with('success', __('Plan successfully activated.'));
            } else {
                return redirect()->back()->with('error', __('Something is wrong.'));
            }
        } else {
            return redirect()->back()->with('error', __('Plan not found.'));
        }
    }

    public function payment($code)
    {
        $planID = \Illuminate\Support\Facades\Crypt::decrypt($code);
        $plan = Plan::find($planID);
        if ($plan) {
            return redirect()->route('stripe', compact('code'))->with('error', __('Your Payment has failed!'));
        } else {
            return redirect()->back()->with('error', __('Plan is deleted.'));
        }
    }
}

resources/views/plan/index.blade.php
@extends('layouts.admin')
@php
    $dir= asset(Storage::url('uploads/plan'));
@endphp
@section('page-title')
   {{__('Plans')}}
@endsection

@section('title')
   {{__('Manage Plan')}}
@endsection
@section('action-btn')
<div class="col-xl-8 col-lg-8 col-md-8 d-flex align-items-center justify-content-between justify-content-md-end" data-bs-placement="top" data-bs-toggle="tooltip"
 data-bs-original-title="{{__('Create')}}">
    @if(App\Models\Utility::getPaymentIsOn() && \Auth::user()->type=='super admin' )
        <a href="#" class="btn btn-sm btn-primary btn-icon m-1" data-bs-toggle="modal"
            data-bs-target="#exampleModal" data-url="{{ route('plans.create') }}"
            data-bs-whatever="{{__('Create New Plan')}}" data-size="lg" data-toggle="tooltip"
            data-bs-title="{{__('Create New Plan')}}"> <span class="text-white"> 
                <i class="ti ti-plus text-white"></i></span>
        </a>
     @endif    
</div>
@endsection
@section('breadcrumb')
    <li class="breadcrumb-item active" aria-current="page">{{__('Plans')}}</li>
@endsection
@section('content')

<div class="row">
@foreach($plans as $plan)
<div class="plan_card">
  <div class="card price-card price-1 wow animate__fadeInUp" data-wow-delay="0.2s" style="visibility: visible; animation-delay: 0.2s; animation-name: fadeInUp;">
    <div class="card-body">
      <span class="price-badge bg-primary">{{$plan->name}}</span>
      @if (\Auth::user()->type == 'company' && \Auth::user()->plan == $plan->id)
          <div class="d-flex flex-row-reverse m-0 p-0 ">
              <span class="d-flex align-items-center ">
                  <i class="f-10 lh-1 fas fa-circle text-success"></i>
                  <span class="ms-2">{{ __('Active') }}</span>
              </span>
          </div>
      @endif
      @if(\Auth::user()->type=='super admin')
      
      <div class="col-12 text-end">
        <div class="action-btn bg-primary ms-2"> 
          <a data-url="{{ route('plans.edit',$plan->id) }}" data-size="lg" data-ajax-popup="true" data-bs-placement="top" data-bs-toggle="tooltip"
 data-bs-original-title="{{__('Edit')}}" data-title="{{__('Edit Plan')}}" data-toggle="tooltip" data-original-title="{{__('Edit')}}"
              class="mx-3 btn btn-sm d-inline-flex align-items-center">
              <i class="ti ti-edit"></i>
          </a>
        </div>
      </div>
        @endif
        <span class="mb-4 p-price m"><span style="font-weight: 600">{{(env('CURRENCY_SYMBOL')) ? env('CURRENCY_SYMBOL') : '$'}}{{$plan->price}}</span><small class="text-sm">{{__('/ Duration : ').__(ucfirst($plan->duration))}}</small></span>
      <p class="mb-0">
        {{ $plan->description }}
      </p>
      
      @if(\Auth::user()->type=='company' && \Auth::user()->plan == $plan->id)
        @if($plan->duration !== 'Unlimited')
            @if(\Auth::user()->type == 'company' && (empty(\Auth::user()->plan_expire_date) || \Auth::user()->plan_expire_date < date('Y-m-d')))
                <p class="mb-0">
                    {{__('Plan Expired') }}
                </p>
            @else
            <p class="mb-0">
                {{__('Plan Expired : ') }} {{!empty( \Auth::user()->plan_expire_date) ?  date('d-m-Y',strtotime(\Auth::user()->plan_expire_date)):'Unlimited'}}
            </p>
            @endif
        @else
        <p class="mb-0">
                {{__('Plan Expired : Unlimited') }}
            </p>
        
        @endif
    @endif
      <ul class="list-unstyled my-4">
        <li>
          <span class="theme-avtar">
            <i class="text-primary ti ti-circle-plus"></i></span>
          {{count($plan->getThemes())}} {{__('Themes')}}
        </li>
        <li>
          <span class="theme-avtar">
            <i class="text-primary ti ti-circle-plus"></i></span>
          {{$plan->business == '-1'?'Unlimited':$plan->business;}} {{__('Business')}}
        </li>
        @if($plan->enable_custdomain == 'on')
          <li>
            <span class="theme-avtar">
              <i class="text-primary ti ti-circle-plus"></i></span>
            {{__('Custom Domain')}}
          </li>
        @else
            <li>

            <span class="theme-avtar">
              <i data-feather="x"  class="text-danger"></i></span>
              <span class="text-danger"> {{__('Custom Domain')}}</span>
            
          </li>
        @endif
        @if($plan->enable_custsubdomain == 'on')
            <li>
            <span class="theme-avtar">
              <i class="text-primary ti ti-circle-plus"></i></span>
            {{__('Sub Domain')}}
          </li>
        @else
            <li>
            <span class="theme-avtar">
              <i data-feather="x"  class="text-danger"></i></span>
              <span class="text-danger"> {{__('Sub Domain')}}</span>
            
          </li>
        @endif
        @if($plan->enable_branding == 'on')
          <li>
            <span class="theme-avtar">
              <i class="text-primary ti ti-circle-plus"></i></span>
              {{__('Branding')}}
          </li>
          @else
            <li>
              <span class="theme-avtar">
                <i data-feather="x" class="text-danger"></i></span>
                <span class="text-danger">{{__('Branding')}}</span>
            </li>    
        @endif
      </ul>
      <div class="row d-flex justify-content-between">
        <div class="col-8">
          @if(\Auth::user()->type == 'company' && (empty(\Auth::user()->plan_expire_date) || \Auth::user()->plan_expire_date < date('Y-m-d')))
          @if(App\Models\Utility::getPaymentIsOn())
                 
              @if($plan->price > 0)
              
                  <div class="d-grid text-center">
                      <a href="{{route('stripe',\Illuminate\Support\Facades\Crypt::encrypt($plan->id))}}"
                          class="btn  btn-primary d-flex justify-content-center align-items-center ">{{ __('Subscribe') }}
                          <i class="fas fa-arrow-right m-1"></i></a>
                      <p></p>
                  </div>

              {{-- @else
                  <a href="#" class="btn  btn-primary d-flex justify-content-center align-items-center">{{__('Free')}}</a> --}}
              @endif
                 
          @endcan
          
      @else
          @if(App\Models\Utility::getPaymentIsOn())
                  @if($plan->id != \Auth::user()->plan && \Auth::user()->type=='company')
                      @if($plan->price > 0)
                      <div class="d-grid text-center">
                          <a href="{{route('stripe',\Illuminate\Support\Facades\Crypt::encrypt($plan->id))}}"
                              class="btn btn-primary btn-sm d-flex justify-content-center align-items-center">{{ __('Subscribe') }}
                              <i class="ti ti-arrow-right ms-1"></i></a>
                          <p></p>
                      </div>
                      {{-- @else
                          <a href="#" class="btn  btn-primary d-flex justify-content-center align-items-center ">{{__('Free')}}</a> --}}
                      @endif
                  @endif
          @endcan
      @endif
        </div>
          @if(\Auth::user()->type != 'super admin' && \Auth::user()->plan != $plan->id)

          @if($plan->id != 1)
                  @if(\Auth::user()->requested_plan != $plan->id)
                      <div class="col-4">
                          <a href="{{ route('send.request',[\Illuminate\Support\Facades\Crypt::encrypt($plan->id)]) }}"
                              class="btn btn-primary btn-icon btn-sm"
                              data-title="{{ __('Send Request') }}" data-bs-placement="top" data-bs-toggle="tooltip"
 data-bs-original-title="{{__('Send Request')}}" data-toggle="tooltip">
                              <span class="btn-inner--icon"><i class="ti ti-arrow-forward-up"></i></span>
                          </a>
                      </div>
                  @else
                      <div class="col-4">
                          <a href="{{ route('request.cancel',\Auth::user()->id) }}"
                              class="btn btn-icon  btn-danger btn-sm" data-bs-placement="top" data-bs-toggle="tooltip"
 data-bs-original-title="{{__('Cancel Request')}}" >
                              <span class="btn-inner--icon"><i class="ti ti-x"></i></span>
                          </a>
                      </div>
                  @endif
          @endif
      @endif
      </div>
      
      
      
    </div>
  </div>
</div>
@endforeach

    </div>
@endsection

resources/views/plan/paymentwall.blade.php
  @php
    $logo=asset(Storage::url('uploads/logo'));
    $company_favicon=Utility::getValByName('company_favicon');
  @endphp
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>@if(Auth::user()->type == 'super admin')  {{config('app.name', 'vCard SaaS')}} @else {{(Utility::getValByName('title_text')) ? Utility::getValByName('title_text') : config('app.name', 'vCard SaaS')}} @endif</title>
    @if(Auth::user()->type == 'super admin')
      <link rel="icon" href="{{$logo.'/favicon.png'}}" type="image" sizes="16x16">
    @else
      <link rel="icon" href="{{(isset($company_favicon) && !empty($company_favicon)?asset(Storage::url($company_favicon)):'favicon.png')}}" type="image" sizes="16x16">
   @endif
    <meta name="csrf-token" content="{{ csrf_token() }}">
  </head>
  @php
    $plan_id= \Illuminate\Support\Facades\Crypt::decrypt($data['plan_id']);
    $plandata=App\Models\Plan::find($plan_id);
 @endphp
  <script src="https://api.paymentwall.com/brick/build/brick-default.1.5.0.min.js"> </script>
  <div id="payment-form-container"> </div>
  <script>
    var brick = new Brick({
      public_key: '{{ $admin_payment_setting['paymentwall_public_key']  }}', // please update it to Brick live key before launch your project
      amount: {{$plandata->price}},
      currency: '{{ env("CURRENCY")  }}',
      container: 'payment-form-container',
      action: '{{route("plan.pay.with.paymentwall",[$data["plan_id"],$data["coupon"]])}}',
      success_url: '{{route("plans.index")}}',
      form: {
        merchant: 'Paymentwall',
        product:  '{{$plandata->name}}',
        pay_button: 'Pay',
        show_zip: true, // show zip code 
        show_cardholder: true // show card holder name 
      }
    });

     brick.showPaymentForm(function(data) {
        if(errors.flag == 1){
        window.location.href ='{{route("callback.error",1)}}';
        }else{
          window.location.href ='{{route("callback.error",2)}}';
        }
    }, function(errors) {
        if(errors.flag == 1){
        window.location.href ='{{route("callback.error",1)}}';
        }else{
          window.location.href ='{{route("callback.error",2)}}';
        }
    });
    
  </script>